### ISSUE TITLE
[Style Checker] Aumentar capacidade de download da ferramenta

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#103]
Gustavo, bom dia.

Semana passada havia conversado com você, que um produtor de XML não conseguiu carregar uma artigo para validar no Style devido ao tamanho superior a 512 kb de um artigo (revista aabc).

Acredito que devemos expandir a capacidade uma vez que a como menciona a usuária do email abaixo (outro caso) as formulas e tabelas codificadas (obrigatoriedade SciELO) aumentaram a quantidade de carácter por XML.

Você poderia trabalhar nisso e me informar quando finalizar para que eu informe da lista?

--------------------------------------------------------------------
Em 2 de dezembro de 2016 14:46, Ana Claudia Ribeiro <editor@e-papers.com.br> escreveu:
Prezada Renata

Tenho mais uma questão que diz respeito à marcação de equações. Hoje tentei verificar um arquivo XML com o http://manager.scielo.org/tools/validators/stylechecker/ e recebi a seguinte mensagem:

The file size is too large! Please select a smaller file.

Acontece que, provavelmente, o arquivo está grande demais porque todas as equações estão marcadas com MathML, e isso torna o arquivo muito mais longo. 

Esse erro é verdadeiro? Existe alguma previsão para aumentar o limite de tamanho dos arquivos no StyleChecker, já que a partir de agora todos os arquivos serão consideravelmente maiores? Lembrando que as equações ainda não são vistas no Previewer (bem como citações, listas e outros itens).

Cordialmente,

Ana Claudia
--------------------------------------------------------------------

**Comment by gustavofonseca** [comment]
O ticket foi movido para https://github.com/scieloorg/scielo-manager/issues/1366
