### ISSUE TITLE
[HTML Previewer] Não mostra células mescladas

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/packtools#131]
As células mescladas não estão aparecendo no HTML Previewer, fazendo com que todas as colunas que deveriam estar mescladas pareçam estar deslocadas. No relatório do XPM as tabelas estão todas OK, conforme mostram os prints abaixo.

**Como está o código:**
`<table-wrap id="t7">
					<label>Tabela 7</label>
					<caption>
						<title>Normas em Percentis para Ambas as Versões da Prova de Nomeação Rápida e para o Escore Total (Número de Acertos e Tempo)</title>
					</caption>
					<table>
						<colgroup>
							<col/>
							<col/>
							<col span="3"/>
							<col span="3"/>
						</colgroup>
						<thead>
							<tr>
								<th align="center" rowspan="2">Ano</th>
								<th align="center" rowspan="2">Percentis</th>
								<th align="center" colspan="3">Precisão</th>
								<th align="center" colspan="3">Tempo (s)</th>
							</tr>
							<tr>
								<th align="center">Parte A</th>
								<th align="center">Parte B</th>
								<th align="center">Total</th>
								<th align="center">Parte A</th>
								<th align="center">Parte B</th>
								<th align="center">Total</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td align="center" rowspan="5">2° Ano</td>
								<td align="center">5</td>
								<td align="center">27</td>
								<td align="center">26</td>
								<td align="center">56</td>
								<td align="center">26</td>
								<td align="center">28</td>
								<td align="center">55</td>
							</tr>
							<tr>
								<td align="center">25</td>
								<td align="center">31</td>
								<td align="center">31</td>
								<td align="center">61</td>
								<td align="center">31</td>
								<td align="center">34</td>
								<td align="center">67</td>
							</tr>
							<tr>
								<td align="center">50</td>
								<td align="center">33</td>
								<td align="center">32</td>
								<td align="center">66</td>
								<td align="center">36</td>
								<td align="center">40</td>
								<td align="center">76</td>
							</tr>
							<tr>
								<td align="center">75</td>
								<td align="center">35</td>
								<td align="center">34</td>
								<td align="center">69</td>
								<td align="center">40</td>
								<td align="center">44</td>
								<td align="center">83</td>
							</tr>
							<tr>
								<td align="center">95</td>
								<td align="center">36</td>
								<td align="center">36</td>
								<td align="center">71</td>
								<td align="center">47</td>
								<td align="center">53</td>
								<td align="center">98</td>
							</tr>
							<tr>
								<td align="center" rowspan="5">3° Ano</td>
								<td align="center">5</td>
								<td align="center">29</td>
								<td align="center">27</td>
								<td align="center">57</td>
								<td align="center">23</td>
								<td align="center">25</td>
								<td align="center">49</td>
							</tr>
							<tr>
								<td align="center">25</td>
								<td align="center">32</td>
								<td align="center">31</td>
								<td align="center">63</td>
								<td align="center">27</td>
								<td align="center">29</td>
								<td align="center">58</td>
							</tr>
							<tr>
								<td align="center">50</td>
								<td align="center">34</td>
								<td align="center">34</td>
								<td align="center">67</td>
								<td align="center">31</td>
								<td align="center">33</td>
								<td align="center">64</td>
							</tr>
							<tr>
								<td align="center">75</td>
								<td align="center">35</td>
								<td align="center">35</td>
								<td align="center">69</td>
								<td align="center">35</td>
								<td align="center">40</td>
								<td align="center">73</td>
							</tr>
							<tr>
								<td align="center">95</td>
								<td align="center">36</td>
								<td align="center">36</td>
								<td align="center">72</td>
								<td align="center">42</td>
								<td align="center">48</td>
								<td align="center">88</td>
							</tr>
							<tr>
								<td align="center" rowspan="5">4° Ano</td>
								<td align="center">5</td>
								<td align="center">30</td>
								<td align="center">27</td>
								<td align="center">57</td>
								<td align="center">22</td>
								<td align="center">25</td>
								<td align="center">48</td>
							</tr>
							<tr>
								<td align="center">25</td>
								<td align="center">32</td>
								<td align="center">32</td>
								<td align="center">65</td>
								<td align="center">27</td>
								<td align="center">28</td>
								<td align="center">55</td>
							</tr>
							<tr>
								<td align="center">50</td>
								<td align="center">34</td>
								<td align="center">34</td>
								<td align="center">68</td>
								<td align="center">29</td>
								<td align="center">33</td>
								<td align="center">62</td>
							</tr>
							<tr>
								<td align="center">75</td>
								<td align="center">35</td>
								<td align="center">35</td>
								<td align="center">70</td>
								<td align="center">34</td>
								<td align="center">36</td>
								<td align="center">69</td>
							</tr>
							<tr>
								<td align="center">95</td>
								<td align="center">36</td>
								<td align="center">36</td>
								<td align="center">72</td>
								<td align="center">41</td>
								<td align="center">47</td>
								<td align="center">88</td>
							</tr>
							<tr>
								<td align="center" rowspan="5">5° Ano</td>
								<td align="center">5</td>
								<td align="center">30</td>
								<td align="center">28</td>
								<td align="center">60</td>
								<td align="center">22</td>
								<td align="center">23</td>
								<td align="center">47</td>
							</tr>
							<tr>
								<td align="center">25</td>
								<td align="center">33</td>
								<td align="center">32</td>
								<td align="center">66</td>
								<td align="center">26</td>
								<td align="center">27</td>
								<td align="center">53</td>
							</tr>
							<tr>
								<td align="center">50</td>
								<td align="center">34</td>
								<td align="center">34</td>
								<td align="center">68</td>
								<td align="center">28</td>
								<td align="center">30</td>
								<td align="center">59</td>
							</tr>
							<tr>
								<td align="center">75</td>
								<td align="center">35</td>
								<td align="center">35</td>
								<td align="center">70</td>
								<td align="center">31</td>
								<td align="center">35</td>
								<td align="center">66</td>
							</tr>
							<tr>
								<td align="center">95</td>
								<td align="center">36</td>
								<td align="center">36</td>
								<td align="center">71</td>
								<td align="center">38</td>
								<td align="center">42</td>
								<td align="center">77</td>
							</tr>
							<tr>
								<td align="center" rowspan="5">Total</td>
								<td align="center">5</td>
								<td align="center">29</td>
								<td align="center">27</td>
								<td align="center">57</td>
								<td align="center">22</td>
								<td align="center">25</td>
								<td align="center">48</td>
							</tr>
							<tr>
								<td align="center">25</td>
								<td align="center">32</td>
								<td align="center">31</td>
								<td align="center">64</td>
								<td align="center">27</td>
								<td align="center">29</td>
								<td align="center">57</td>
							</tr>
							<tr>
								<td align="center">50</td>
								<td align="center">34</td>
								<td align="center">33</td>
								<td align="center">67</td>
								<td align="center">31</td>
								<td align="center">34</td>
								<td align="center">65</td>
							</tr>
							<tr>
								<td align="center">75</td>
								<td align="center">35</td>
								<td align="center">35</td>
								<td align="center">69</td>
								<td align="center">35</td>
								<td align="center">39</td>
								<td align="center">74</td>
							</tr>
							<tr>
								<td align="center">95</td>
								<td align="center">36</td>
								<td align="center">36</td>
								<td align="center">71</td>
								<td align="center">43</td>
								<td align="center">50</td>
								<td align="center">91</td>
							</tr>
						</tbody>
					</table>
				</table-wrap>`

**Como aparece no XPM:** 
![erro-htmlprev2](https://cloud.githubusercontent.com/assets/26901197/25746336/647f2bb2-3179-11e7-8262-092f1903820d.png)

**Como aparece no HTML Previewer:**
![erro-htmlprev](https://cloud.githubusercontent.com/assets/26901197/25746214/cb4b9412-3178-11e7-974c-4abd093978b9.png)

**Seguem arquivos utilizados para teste.**

[2175-3563-pusf-22-01-00035.pdf](https://github.com/scieloorg/packtools/files/979023/2175-3563-pusf-22-01-00035.pdf)
[2175-3563-pusf-22-01-00035.txt](https://github.com/scieloorg/packtools/files/979022/2175-3563-pusf-22-01-00035.txt)

**Comment by cinthia-vieira** [comment]
O erro persiste, como relatado pelo prestador João Bosco na lista de discussão.

Segue o link do tópico:
https://groups.google.com/d/topic/scielo-xml/LRvAIBTWKR0/discussion

**Comment by gustavofonseca** [comment]
O pré-visualizador foi reimplementado. O erro não é mais reproduzido.
