### ISSUE TITLE
Style checker apresenta erros que aparentemente não estão de acordo com a documentação

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/packtools#139]
![image](https://user-images.githubusercontent.com/505143/37155282-44b61b3a-22c1-11e8-9efe-b70332913c8d.png)

Arquivo anexo.
[0066-782X-abc-108-04-383-v2.zip](https://github.com/scieloorg/packtools/files/1793359/0066-782X-abc-108-04-383-v2.zip)

**Comment by robertatakenaka** [comment]
@alexxpsilva Por favor, inclua como deveria apresentar o XML e coloque link para a documentação SPS ou JATS.

**Comment by alexxpsilva** [comment]
@robertatakenaka o XML está se apresentando de acordo, só não deveria acusar o erro.

Link [SPS](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.7-branch/tagset/elemento-response.html)

Link [JATS](http://jats.nlm.nih.gov/publishing/tag-library/1.1/element/response.html)

**Comment by gustavofonseca** [comment]
@alexxpsilva, anexe por gentileza o XML aqui no ticket. Provavelmente vc terá que alterar a extensão do arquivo para .txt para que o Github aceite.

**Comment by alexxpsilva** [comment]
@gustavofonseca segue o arquivo em .txt anexo.
[0066-782X-abc-108-04-383-v2.txt](https://github.com/scieloorg/packtools/files/1804313/0066-782X-abc-108-04-383-v2.txt)

**Comment by gustavofonseca** [comment]
O comportamento do stylechecker está de acordo com http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.7-branch/narr/artigo-comentado.html

**Comment by gustavofonseca** [comment]
Vou marcar esse ticket como inválido por enquanto. Caso eu tenha interpretado a especificação de maneira errada me informe por gentileza.

**Comment by lpanebr** [comment]
Na minha opinião a documentação[1] está equivocada ao indicar que o related-article-type deve obrigatoriamente ter o valor "commentary-article".

Segundo JATS 1.1[2] o `related-article-type` pode receber outros valores.

[1] http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.7-branch/narr/artigo-comentado.html
[2] https://jats.nlm.nih.gov/publishing/tag-library/1.1/attribute/related-article-type.html

**Comment by gustavofonseca** [comment]
@lpanebr, na realidade o atributo *related-article-type* pode assumir os valores *corrected-article*, *commentary-article*, *letter*, *partial-retraction* ou *retracted-article* [1]. 

Mas o teu comentário me fez revisitar a documentação e regras de validação e eu acabei ficando inseguro sobre a minha resposta ao @alexxpsilva em https://github.com/scieloorg/packtools/issues/139#issuecomment-372801641. Vou desmarcar esse ticket como inválido e verificar novamente amanhã.

[1]http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.7-branch/tagset/elemento-related-article.html

**Comment by alexxpsilva** [comment]
@gustavofonseca, na verdade o Style ele não está prevendo o elemento "response" no article-type "letter, e segundo a [JATS é permitido](https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/response.html).

Posso estar enganado, mas o elemento "response" não é de uso específico para o tipo "letter, um artigo original, ou até mesmo uma discussão pode gerar uma resposta, fazendo necessário o uso de uma resposta.

**Comment by gustavofonseca** [comment]
@alexxpsilva, a regra implementada atualmente no stylechecker diz que se um elemento _response_ possui o valor _reply_ no seu atributo _response-type_, o valor do atributo _article/@article-type_ deve ser igual a _article-commentary_. Você pode encontrar algumas discussões envolvendo essa regra que, para ser sincero, nunca me cheirou bem. Veja o link https://github.com/scieloorg/scielo_publishing_schema/issues/254.

**Comment by alexxpsilva** [comment]
@gustavofonseca, compreendi, não tinha conhecimento dessa discussão.

Neste caso, voce acha melhor mantermos dessa forma? Seja qual for a definição, temos que passar nas ferramentas de validações para ver se algum erro é apresentado, e se necessário abrir a discussão novamente para revermos essa questão.

**Comment by gustavofonseca** [comment]
@alexxpsilva, vou flexibilizar um pouco mais as validações do stylechecker sobre o elemento _response_. Acho que as validações estão assumindo coisas além do explicitado na especificação.

**Comment by alexxpsilva** [comment]
Certo @gustavofonseca, após essa flexibilização farei o teste novamente.
