### ISSUE TITLE
[Style Checker] Valida os arquivosque deveriam ser invalidados de acordo com os criterios

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/packtools#142]
Ao realizar o teste na segunda-feira (05-03-18) a ferramenta não validada contra as regras SciELO Brasil arquivos que não possuíssem os itens abaixo:

- Autoria;
- Afiliação;
- Referência.

Hoje, ao validar um arquivo sem nenhum desses itens o arquivo deu como valido.

**Comment by gustavofonseca** [comment]
@alexxpsilva, os arquivos estão codificados conforme a SPS-1.8?

**Comment by alexxpsilva** [comment]
@gustavofonseca sim, 1.8.
Abaixo segue exemplo de um arquivo sem xref de afiliação e, sem afiliação alguma.

![style_criterios](https://user-images.githubusercontent.com/15328777/37402142-375bab1a-2769-11e8-9626-ffeaa0709b46.png)

Na versão 1.7 é apresentado o mesmo erro.

**Comment by gustavofonseca** [comment]
@alexxpsilva, os erros que estão sendo exibidos na imagem no seu último comentário são de referências entre _id_ e _rid_, e de fato configuram erro na estrutura do XML.

**Comment by alexxpsilva** [comment]
@gustavofonseca , coloquei dois xml's anexo.

1 - sem referências
2 - sem contrib-group e sem afiliação.

Ambos foram validados.

[bak-sem-contrib-sem-aff.txt](https://github.com/scieloorg/packtools/files/1811640/bak-sem-contrib-sem-aff.txt)
[bak-sem-referencias.txt](https://github.com/scieloorg/packtools/files/1811641/bak-sem-referencias.txt)

**Comment by alexxpsilva** [comment]
@gustavofonseca, realizei o teste com o arquivo sem contrib-group, e está correto, agora acusa o erro abaixo:

STYLE ERROR | Element 'article-meta', Missing element contrib-group.

apenas para confirmar, realizei o mesmo teste mencionado no ticket, tirando todas as afiliações do arquivo e xrefs de afiliações do arquivo, antes apresentava o erro, que você mencionou como erro na estrutura do XML, mas nessa nova versão o arquivo é validado. O correto seria aparecer como invalidado, certo?

**Comment by gustavofonseca** [comment]
@alexxpsilva, o teste que vc menciona foi usando o arquivo [bak-sem-contrib-sem-aff.txt](https://github.com/scieloorg/packtools/files/1811640/bak-sem-contrib-sem-aff.txt)?

**Comment by alexxpsilva** [comment]
@gustavofonseca , não. Usei o arquivo "bak-sem-rerencias".

**Comment by gustavofonseca** [comment]
@alexxpsilva, o stylechecker de homolog.manager.scielo.org foi atualizado novamente, agora com as validações de back, ref-list, ref e afiliações não referenciadas por contribuidores.

**Comment by alexxpsilva** [comment]
@gustavofonseca, realizei os testes novamente e agora acusa erro para os 3 casos.

dúvida: para o teste mencionado alto, do contrib-group "solto" no arquivo sem referências, ele acusa o erro abaixo.

![semaffs-semxrefs-semrefs](https://user-images.githubusercontent.com/15328777/37519667-c8c04c4c-28f8-11e8-9128-0eaf494f581b.png)

além do erro apresentado, não deveria acusar algum outro erro referente a ausência das afiliações? Caso esteja correto dessa forma, pode fechar o ticket.

**Comment by alexxpsilva** [comment]
@gustavofonseca, testei novamente novamente, só que agora acrescentando um elemento ref-list, mantendo o arquivo sem afiliações e xref's correspondentes, e o arquivo é validado.

Segue XML anexo.
[bak-sem-affs-sem-xrefs.txt](https://github.com/scieloorg/packtools/files/1819385/bak-sem-affs-sem-xrefs.txt)

**Comment by gustavofonseca** [comment]
@alexxpsilva, eu não consegui entender seus comentários em https://github.com/scieloorg/packtools/issues/142#issuecomment-373693465. Você descreve o que aconteceu mas não fica claro para mim se é o que vc esperava ou não.

**Comment by alexxpsilva** [comment]
@gustavofonseca, no meu primeiro comentário, que contém a imagem com o erro eu estava com dúvidas se a ausência de afiliação também estava sendo validada já que só tinha acusado erro para a ausência de back.

no segundo comentário, fiz um novo teste, usando o mesmo arquivo, mas acrescentei o elemento ref-list em ```back``` e o arquivo foi validado, ou seja, a ferramenta não está invalidando arquivos que não possuem afiliação, que seria o correto.

**Comment by gustavofonseca** [comment]
@alexxpsilva, entendi. O problema foi resolvido no commit b48b6e5
