### ISSUE TITLE
[Style Checker] Elemento <country>

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/packtools#146]
Para SciELO Brasil o elemento é obrigatório, e validado contra as regras SciELO Brasil está ok, porém para a rede não o elemento não é obrigatório.

A ferramenta acusa o erro abaixo quando o elemento "country" está ausente

![style_country](https://user-images.githubusercontent.com/15328777/37404466-b83cdb12-2770-11e8-9b11-0e558705940b.png)

**Comment by gustavofonseca** [comment]
Corrigido no commit 07c2b11, mas apenas para a versão 1.8 da especificação.
