### ISSUE TITLE
[Style Checker] Exige elemento <back> para Errata e Retratação

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/packtools#147]
a Ferramente exige que arquivos com article-type do tipo "correction" e "retraction" possuam o elemento ```<back>```

![style_errata_retratacao](https://user-images.githubusercontent.com/15328777/37525547-f047fd92-290b-11e8-8536-51fcc1cba7eb.png)

xml's anexos.

[acb-errata.txt](https://github.com/scieloorg/packtools/files/1819499/acb-errata.txt)
[bjmbr-retratacao.txt](https://github.com/scieloorg/packtools/files/1819500/bjmbr-retratacao.txt)

**Comment by gustavofonseca** [comment]
Corrigido em 62c0ac4

**Comment by alexxpsilva** [comment]
@gustavofonseca, agora exige afiliação conforme o erro apresentado abaixo

![style_errata_retratacao_2](https://user-images.githubusercontent.com/15328777/37770753-37b2874a-2db4-11e8-9908-3ba785fdb474.png)

apenas lembrando, article-type do tipo "correction", "retration" e "partial-retraction" não possuem autoria, consequentemente  não possuem afiliações, e também não possuem referências.

para os demais valores de article-type os elementos citados acima são obrigatórios.

**Comment by gustavofonseca** [comment]
@alexxpsilva, o ponto que vc levantou no comentário https://github.com/scieloorg/packtools/issues/147#issuecomment-375291192 está relacionado com o ticket https://github.com/scieloorg/packtools/issues/142, e não com este aqui.

**Comment by alexxpsilva** [comment]
@gustavofonseca, correto. Porém Errata e Retratação não são documentos citáveis, por isso especificamente pra esses tipos os itens obrigatórios do ticket #142 não se aplicam neste caso.
