### ISSUE TITLE
Apresentar todos os autores

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/packtools#159]
Aparentemente está mostrando até 10 autores por estar limitando ao valor informado por **MAX_CONTRIB**.

relacionado com https://github.com/scieloorg/opac/issues/857

Para solucionar, remover ``[position()&lt;=number($MAX_CONTRIB)]`` de **packtools/packtools/catalogs/htmlgenerator/v2.0/article-meta-contrib.xsl**, pois isso está filtrando a quantidade de autores.
Também pode ser removido ``<xsl:if test="count(contrib)&gt;number($MAX_CONTRIB)"> ... </xsl:if>``.

A responsabilidade de apresentar autores até 10 é do opac (**opac/opac/webapp/static/js/scielo-article.js**).

Haverá a necessidade de transformar os arquivos:
[scielo_br_10autores.txt](https://github.com/scieloorg/packtools/files/2624924/scielo_br_10autores.txt)
[scielo_spa_10autores.txt](https://github.com/scieloorg/packtools/files/2624925/scielo_spa_10autores.txt)

**Comment by patymori** [comment]
Problema corrigido e validado no OPAC.
