### ISSUE TITLE
[DOIMultilingue] Fazer validação de DOI em sub-article

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/packtools#167]

**Comment by RPostalli** [comment]
Testado: Cinthia, Joyce Natalie.

STATUS: OK

**Comment by RPostalli** [comment]
Testado: Cinthia, Joyce Natalie.

STATUS: BUG

ainda exige obrigatoriedade de DOI pra tradução, tanto no SPS 1.9 quanto no 1.8

**Comment by JoyceRaphaela** [comment]
Segue em anexo arquivo onde a obrigatoriedade de DOI para tradução está sendo exigida:
[2179-8966-rdp-10-1-129.zip](https://github.com/scieloorg/packtools/files/3019267/2179-8966-rdp-10-1-129.zip)

**Comment by gustavofonseca** [comment]
@robertatakenaka, não há nos critérios ou em qualquer comunicação oficial uma regra que obriga que todas as traduções possuam DOI. Aparentemente até o momento trata-se de uma recomendação que deverá ser operacionalizada para os documentos depositados sob o prefixo 10.1590.
