### ISSUE TITLE
Tornar obrigatória a presença de DOI em traduções

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#172]
Esta regra se aplica exclusivamente para SciELO Brasil.

Ticket relacionado: https://github.com/scieloorg/scielo_publishing_schema/issues/175

**Comment by RPostalli** [comment]
Testado, ver comentário em: https://github.com/scieloorg/packtools/issues/167
OBS: DOI para tradução não é obrigatório. Se tiver validar (mesmas validações do DOI de artcile). Se tiver deve ser DOI diferente do DOI de article.

**Comment by gustavofonseca** [comment]
Até a data atual esta regra não foi definida nos critérios SciELO ou em qualquer outra comunicação formal de SciELO.

**Comment by lpanebr** [comment]
Caso scielo Brasil venha a exigir DOI único para as traduções é bom avisar os Editores das revistas com bastante antecedência. Pode ser um pequeno pesadelo ter que atualizar dezenas de artigos PDF e XML em dezenas de revistas de uma hora pra outra.
