### ISSUE TITLE
Retirar suporte para JATS 1.0

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#173]
A versão 1.9 da SciELO PS não suportará mais a JATS 1.0 mas apenas a 1.1.

Ticket relacionado: https://github.com/scieloorg/scielo_publishing_schema/issues/792

**Comment by RPostalli** [comment]
Teste: Cinthia, Natalie, Joyce.

STATUS: BUG

Não é apontado erro para JATS 1.0

**Comment by RPostalli** [comment]
Teste: Cinthia, Natalie, Joyce.

STATUS: BUG

considera válido XML 1.9 com JATS 1.0

**Comment by natalieakemi** [comment]
[1807-5932-clin-74-6.zip](https://github.com/scieloorg/packtools/files/3019244/1807-5932-clin-74-6.zip)

**Comment by gustavofonseca** [comment]
Deixar de acusar erro ao encontrar referência à JATS Publishing 1.0 não é muito grave, haja vista que se o XML não fizer uso de marcações exclusivas da versão mais recente da JATS, não faz diferença. Em casos onde o XML apresenta elementos exclusivos da versão 1.1 mas referencia a 1.0, o XML será considerado inválido pela validação contra a DTD.
