### ISSUE TITLE
Suportar *visual abstracts*

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#178]
Esta regra deve valer para todos os usuários da especificação, e não apenas para SciELO Brasil, a partir da sps-1.9.

```
...
<abstract abstract-type="graphical">
  <title>Resumo gráfico</title>
  <p>
    <fig id="vf01">
      <caption>
        <title>Título</title>
      </caption>
      <graphic xlink:href="1234-5678-zwy-12-04-0123-vs01.tif"/>
    </fig>
  </p>
</abstract>
...
``` 

```
...
<article-meta>
    ...
    <trans-abstract abstract-type="graphical" xml:lang="en">
      <title>Visual Abstract</title>
      <p>
        <fig id="vf01">
          <caption>
            <title>Title</title>
          </caption>
          <graphic xlink:href="1234-5678-zwy-12-04-0123-vs01.tif"/>
        </fig>
      </p>
    </trans-abstract>
    ...
</article-meta>
...
```

Referências:
* https://github.com/scieloorg/scielo_publishing_schema/issues/773
* https://github.com/scieloorg/scielo_publishing_schema/issues/774
* https://github.com/scieloorg/scielo_publishing_schema/issues/825

**Comment by RPostalli** [comment]
Testado: Cinthia, Joyce, Natalie

STATUS: BUG

não considera esperado o atributo @xml:lang em visual abstract

**Comment by gustavofonseca** [comment]
Resolvido em 8df059d
