### ISSUE TITLE
Validação para page-counts em Publicação Contínua

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#179]
https://github.com/scieloorg/PC-Programs/issues/2796

**Comment by RPostalli** [comment]
Testado: Cinthia, Joyce, Natalie

STATUS: BUG

Não apresenta erro na presença de  `<page-counts>`

**Comment by gustavofonseca** [comment]
Mas isso não faz parte da sps-1.9, ou faz?

**Comment by RPostalli** [comment]
Isso é válido desde a versão SPS 1.8.

**Comment by gustavofonseca** [comment]
Ok, vou marcar como um bug.

**Comment by gustavofonseca** [comment]
Depois de analisar melhor este ticket, decidi fechá-lo marcando-o como inválido pelos seguintes motivos: (i) a especificação SciELO PS é agnóstica ao modelo de publicação e (ii) não se trata de uma regra de SciELO PS (fiz uma busca extensa pela documentação e não encontrei nada sobre isso. Se eu estiver enganado peço que informe o link ao reabrir este ticket).

**Comment by RPostalli** [comment]
@gustavofonseca o ticket não é inválido. Existe a necessidade de podermos representar visual abstract em mais de um idioma em um article. E assim foi documentado no SPS 1.9 https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-abstract.html

Ou seja para SPS se usar trans-abstrac faz-se obrigatório o uso de xml:lang.

**Comment by RPostalli** [comment]
@gustavofonseca OK, teremos a validação em XC e XPM.
