### ISSUE TITLE
Retirar validação de obrigatoriedade de xref e ref para Editorial

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#180]
https://github.com/scieloorg/scielo_publishing_schema/issues/782

**Comment by RPostalli** [comment]
Testado: Cintia, Joyce, Natalie

STATUS: BUG

a obrigatoriedade de xref e ref foi retirada de todos os documentos, e não só editorial.

**Comment by gustavofonseca** [comment]
Negativo. A obrigatoriedade não existe para apenas para os tipos _correction_, _retraction_, _partial-retraction_ e _editorial_, conforme descrito na documentação. 

Me envie por gentileza um exemplo que reproduza o erro.

**Comment by RPostalli** [comment]
Testado: Cintia, Joyce, Natalie

STATUS: BUG

considera válidos outros tipos de documentos sem xref e ref, como research-article, tanto no SPS 1.9 quanto no 1.8

**Comment by cinthia-vieira** [comment]
XML referente a este erro:
[1678-4596-cr-49-03-e20180045.zip](https://github.com/scieloorg/packtools/files/3019240/1678-4596-cr-49-03-e20180045.zip)

**Comment by gustavofonseca** [comment]
> XML referente a este erro:
> [1678-4596-cr-49-03-e20180045.zip](https://github.com/scieloorg/packtools/files/3019240/1678-4596-cr-49-03-e20180045.zip)

O documento em anexo é do tipo `research-article` e o validador está emitindo a mensagem `Element 'article': Missing element back.` conforme esperado.

**Comment by RPostalli** [comment]
@gustavofonseca eu acho que o Style nunca considerou a validação dos 5 itens dos Critérios.
Para[ todos os tipos](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-article.html) de documento (com exceção de errata, retratação e editorial) quando não tem xref e ref-list teria que acusar erro.

Trata-se de uma regra específica para SiELO Brasil: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/scielo-brasil.html

O Style não vai contemplar validação de Critérios? Caso não pode fechar o ticket.

**Comment by gustavofonseca** [comment]
A validação dos 5 itens está implementada no stylechecker e o erro é levantado. No caso do exemplo, `Element 'article': Missing element back`.
