### ISSUE TITLE
Suportar @article-type="data-article"

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#182]
https://github.com/scieloorg/scielo_publishing_schema/issues/800

**Comment by RPostalli** [comment]
Testado: CInthia, Joyce, Natalie.

STATUS: BUG

Não suporta "data-article":
Element 'article', attribute article-type: Invalid value 'data-article'.

**Comment by natalieakemi** [comment]
[1678-9849-rsbmt-52-e20180139.zip](https://github.com/scieloorg/packtools/files/3010208/1678-9849-rsbmt-52-e20180139.zip)

**Comment by gustavofonseca** [comment]
Corrigido.
