### ISSUE TITLE
SPS 1.9 Novas datas de publicação em <pub-date>

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#183]
https://github.com/scieloorg/scielo_publishing_schema/issues/565

**Comment by RPostalli** [comment]
Teste de @cinthia-vieira

STATUS: BUG

#. SPS 1.9 Novas datas de publicação em `<pub-date>`

- Não valida a obrigatoriedade de `<day>` e `<month>`: não acusa erro na ausência dessas tags, e aceita `<season>` em @date-type="pub";
- Não valida obrigatoriedade de data com atributo @date-type="pub";
- Não valida obrigatoriedade de data com atributo @date-type="collection";
- Não considera errado o uso de `<day>` para `<pub-date>` com atributo @date-type="collection"
- VALIDA valores de @date-type (comportamento esperado).

**Comment by gustavofonseca** [comment]
Corrigido em 8db2772, 2f36337 e 4d6e2e9

**Comment by RPostalli** [comment]
Testado: Cinthia, Joyce, Natalie.

STATUS: BUG

- não acusa falta de collection;
- collection aceita 'day';

**Comment by cinthia-vieira** [comment]
XML referente a este erro: 
[0066-782X-abc-112-02-0119.zip](https://github.com/scieloorg/packtools/files/3019217/0066-782X-abc-112-02-0119.zip)

**Comment by gustavofonseca** [comment]
<img width="637" alt="Screen Shot 2019-03-28 at 13 56 40" src="https://user-images.githubusercontent.com/161335/55177171-802fff80-517a-11e9-9915-bbc199e00b0b.png">

Para o elemento pub-date, a validação está correta. De fato o valor de `@date-type` é inválido e está faltando o elemento obrigatório `pub-date[@date-type="pub"]`, conforme consta na documentação (https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-pub-date.html)

> * não acusa falta de collection;

`pub-date[@date-type="collection"]` não é obrigatório segundo a documentação.

> * collection aceita 'day';

<img width="748" alt="Screen Shot 2019-03-28 at 14 01 18" src="https://user-images.githubusercontent.com/161335/55177453-35fb4e00-517b-11e9-96fb-c75375915129.png">

Eu alterei o XML que você anexou conforme é possível ver na imagem acima. Repare no erro que diz `Element 'pub-date': Unexpected element day.`.

**Comment by cinthia-vieira** [comment]
Validado. Tag `<day>` é considerada elemento inesperado em `"collection"`

**Comment by gustavofonseca** [comment]
@cinthia-vieira, posso fechar este ticket?

**Comment by RPostalli** [comment]
@gustavofonseca para SciELO a tag collection nunca terá a tag day, uma vez que estas datas representam periodicidade ( envolve processamento relacionado a mês(es) + ano). O Style não vai abarcar esta validação? Caso não, pode fechar o ticket sim.

**Comment by gustavofonseca** [comment]
A validação foi implementada. Estou fechando este ticket.
