### ISSUE TITLE
Editor que exibe o XML anotado com os erros de validação não é exibido corretamente

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#191]
<img width="742" alt="Screen Shot 2019-04-10 at 10 04 25" src="https://user-images.githubusercontent.com/161335/55880943-422ad680-5b91-11e9-91e5-e55de48cec7f.png">

**Comment by gustavofonseca** [comment]
Notei que em nenhum dos commits do branch `viewer`, onde estão sendo desenvolvidas as funcionalidades da aplicação web para validação e pré-visualização, está presente o código fonte do codemirror. @cesarbruschetta observou que a não inclusão dos arquivos se deu por conta do `.gitignore` que ignora diretórios de nome `lib`.

**Comment by gustavofonseca** [comment]
@cesarbruschetta, você pode, por gentileza, assumir esta atividade?

**Comment by cesarbruschetta** [comment]
https://github.com/scieloorg/packtools/pull/192
