### ISSUE TITLE
Gerar nova Versão do Packtools

### ISSUE THREAD

**Issue by cesarbruschetta** [scieloorg/packtools#197]
## Descrição

Precisamos gerar uma nova versão do lib, para incorporar o PR #196 e assim poder atualizar as demais aplicações que depende desse código e em especial o **OPAC** que esta aguardando essa implementação para pode seguir com a conclusão do issue scieloorg/opac#1180 

## Referencias
#196 
scieloorg/opac#1180

**Comment by gustavofonseca** [comment]
Foi lançada a versão 2.5.1.
