### ISSUE TITLE
Ausência de resumos na página do artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/packtools#215]
### Descrição do problema
Apresenta ausência de resumos em documentos que foram representados por XML, com sub-article e há mais versões de resumos que versões de texto completo.

### Passos para reproduzir o problema

Texto em português apresenta resumo em português
https://new.scielo.br/article/asoc/2017.v20n1/43-64/pt 

Texto em inglês apresenta resumo em inglês e espanhol
https://new.scielo.br/article/asoc/2017.v20n1/43-64/en/

PDF em inglês (resumo em inglês, português e espanhol):
- https://new.scielo.br/pdf/asoc/2017.v20n1/43-64/en
PDF em português (resumo em inglês, português e espanhol):
- https://new.scielo.br/pdf/asoc/2017.v20n1/43-64/pt

### Comportamento esperado
Todos os resumos devem ser apresentados no texto completo, independentemente do idioma do texto.

### Screenshots ou vídeos
<img width="545" alt="Captura de Tela 2019-11-12 às 10 38 17" src="https://user-images.githubusercontent.com/505143/68676323-912a5700-0538-11ea-8753-bcf1126de4fa.png">
<img width="545" alt="Captura de Tela 2019-11-12 às 10 38 01" src="https://user-images.githubusercontent.com/505143/68676331-95567480-0538-11ea-8252-cf73c5db5071.png">

### Anexos

Segue a especificação:
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-trans-abstract.html

### Ambiente utilizado
n/a

**Comment by patymori** [comment]
As discussões estão sendo desenvolvidas no ticket scieloorg/Web/issues/698

**Comment by patymori** [comment]
Após a alteração, sempre exibe um título de seção "Abstract", mesmo quando o artigo não possue resumo.
