### ISSUE TITLE
Implementar um otimizador de pacotes SPS

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/packtools#216]
### Descrição da tarefa

Espera-se que o packtools concentre a funcionalidade de otimizar pacotes SPS agindo diretamente nos ativos digitais. Dado um pacote SPS contendo ativos digitais não otimizados para `web` (ex: `.tif`) espera-se que a otimização gere versões em outros formatos (ex: WebP, PNG, JPEG).

Após a otimização dos ativos digitais é necessário alterar o XML para que o mesmo passe a conhecer as versões [alternativas](https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/alternatives.html) dos novos assets.

### Subtarefas

- [ ] Discutir os formatos de imagens adequados para Web;
- [ ] Discutir a interface de linha de comando adotada para o packtools;
    - ex: `comando pacote_sps.zip --asset-size=1024x960 860x540 250x100`
    - ex: `comando pacote_sps.zip --asset-size-optimizer 3x`(teriamos algo como a imagem original e 3 versões reduzidas proporcionalmente)
- [ ] Discutir os valores adequados para o `specific-use` que serão utilizados nas versões alternativas.
- [ ] Codificar a proposta de implementação já consolidada;

## Considerações e notas
Esta é uma issue inicial para que haja um amadurecimento sobre as ideias que serão implementadas, pode-se ler um condensado do nosso brainstorm [neste comentário](https://github.com/scieloorg/opac/issues/1456#issuecomment-561181174).

**Comment by lpanebr** [comment]
> Após a otimização [...] é necessário alterar o XML [...].

Não sei se já viram isto, mas talvez seja relevante para essa questão:
 - No PMC não é necessário incluir a extensão dos arquivos no XML, conforme pode ser observado nos [fully tagged samples](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/style.html#samples)

```xml
<graphic xlink:href="pone.0052470.g002"/>
```

**Comment by gustavofonseca** [comment]
> > Após a otimização [...] é necessário alterar o XML [...].
> 
> Não sei se já viram isto, mas talvez seja relevante para essa questão:
> 
>     * No PMC não é necessário incluir a extensão dos arquivos no XML, conforme pode ser observado nos [fully tagged samples](https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/style.html#samples)
> 
> 
> ```
> <graphic xlink:href="pone.0052470.g002"/>
> ```

@lpanebr, bem observado. É uma abordagem interessante, mas problemática no nosso entendimento pois se baseia no implícito e não no explícito. No nosso design decidimos utilizar o XML como fonte autoritativa dos dados do documento tanto para uso interno nos nossos sistemas de informação quanto para distribuição e reuso. Pensamos que a distribuição e reuso são impactadas negativamente quando nos apoiamos em aspectos implícitos.

**Comment by lpanebr** [comment]
sim, aspectos implícitos definitivamente prejudicam o reuso!

Eu não conhecia essa decisão de design. Vou ter isso em mente quando fizer comentários futuros.

Obrigado!

**Comment by robertatakenaka** [comment]
@joffilyfe @jamilatta @gustavofonseca @patymori 
`Discutir os formatos de imagens adequados para Web;
`
- caso venha em .tiff, convertemos para qualquer formato que seja adequado para web, caso contrário não o faremos num primeiro momento

```
2. Discutir a interface de linha de comando adotada para o packtools;
    ex: comando pacote_sps.zip --asset-size=1024x960 860x540 250x100
    ex: comando pacote_sps.zip --asset-size-optimizer 3x(teriamos algo como a imagem original e 3 versões reduzidas proporcionalmente)
```
- acho que podemos trabalhar com 3 valores prédefinidos, mas caso o asset-size seja passado, adotamos os valores passados. 

`Discutir os valores adequados para o specific-use que serão utilizados nas versões alternativas.`

https://jats.nlm.nih.gov/publishing/tag-library/1.2/attribute/specific-use.html
```
**specific-use**
**Specific Use**
_Specifies distinctions in the applicability of a particular element._
**Usage**
This Tag Set does not limit the uses of the @specific-use attribute. For example, @specific-use could be used to mark content (such as a paragraph, note, or section) that: 
    - only appears in one format (“web-only”, “print-only”, “voice-only”, “electronic-only”);
    - is intended for a particular audience (the set “for-teachers” versus the set for “for-students”, or the sets “for-doctors”, “for-nurses”, or “for-the-patient”);
    - is organization-sensitive material (“company-only” or “limited-distribution”) and thus not shown to all audiences;
    - has a specific use that cannot be determined from the content of the material, for example, is part of continuing medical or legal education (“CME”); or
    - contains an accessibility alternative that screen readers could “read” but that visual display devices would ignore. (See also the @alt attribute.)
```
Talvez usar a combinação de `@specific-use` para dizer se é do tamanho pequeno, médio e grande e em `@content-type` especificar o tamanho, pois o valor que seria considerado hoje como pequeno pode não ser no futuro...

**Comment by gustavofonseca** [comment]
De acordo com a [JATS4R](https://jats4r.org/display-objects), o atributo `@specific-use` não deveria ser utilizado para representar `diferenças na aparência ou formatação`, portanto ao utilizá-lo para indicar o tamanho nós estaríamos violando a recomendação. A JATS4R não diz nada sobre o uso do `@content-type`. 

Caso a gente queira estar em conformidade com a JATS4R, uma alternativa seria como `@specific-use="scielo-web"`. 

Não estou seguro sobre indicarmos as dimensões das imagens, mas caso seja necessário acredito que seria `@content-type="scielo-50x50"`. O que acham?

**Comment by robertatakenaka** [comment]
@gustavofonseca concordo com @specific-use="scielo-web" somente se servir para scielo, mas não seria o caso de ser "web" ou "web-only" apenas? o que a nossa web seria diferente das demais?

**Comment by jamilatta** [comment]
@gustavofonseca @joffilyfe @patymori 

Acredito que seja necessário adicionar a Parati, para termos certeza dos tamanhos necessários, já que temos a interface mobile para ser atendido pelas imagens!  

Concordo com a @robertatakenaka de utilizarmos **@specific-use="web"**! 

Assim como em diversos sites com a mesma necessidade de disponibilizar as imagens, sugiro disponibilizar o download para o formato de maior qualidade fornecida pelo autor/periódico do artigo, como por exemplo o formato .tiff, exif, e/ou svg.

Outro ponto que devemos conversar é a opção do formato para exibição no site, o formato **webp** tem como proposta diminuir em até 40% o tamanho da imagem, sem perda de qualidade, isso diminuiria o tráfego e o custo de armazenamento.

Também existe a opção de compressão dos formatos **png** e **jpeg**, exemplo de boas compressões realizadas: https://tinypng.com/

Não cosiderem e não considero, as otmizações nas imagens algo necessário para a realização dessa atividade, mas quero deixar registrados algumas opções que temos para essa fase de tratamento das imagens.

**Comment by jamilatta** [comment]
@robertatakenaka @gustavofonseca @joffilyfe @patymori

Outro ponto que fiquei pensando será que devemos ter também o tamanho em **bytes** de cada formato?

**Comment by joffilyfe** [comment]
> De acordo com a [JATS4R](https://jats4r.org/display-objects), o atributo `@specific-use` não deveria ser utilizado para representar `diferenças na aparência ou formatação`, portanto ao utilizá-lo para indicar o tamanho nós estaríamos violando a recomendação. A JATS4R não diz nada sobre o uso do `@content-type`.
> 
> Caso a gente queira estar em conformidade com a JATS4R, uma alternativa seria como `@specific-use="scielo-web"`.
> 
> Não estou seguro sobre indicarmos as dimensões das imagens, mas caso seja necessário acredito que seria `@content-type="scielo-50x50"`. O que acham?
----
> @gustavofonseca concordo com @specific-use="scielo-web" somente se servir para scielo, mas não seria o caso de ser "web" ou "web-only" apenas? o que a nossa web seria diferente das demais?
> Também acho que o content-type não precisa de ser scielo-, pois 50x50 acho que universal.

Acho que vocês **estão corretos** e o uso do `content-type` associado com o `specific-use` **é adequado**. O comentário da @robertatakenaka é bem pertinente, a principio não deveria haver diferenças entre um `web` e `web-scielo`. 

Se não delimitarmos o `specific-use` ao contexto de `scielo-` poderíamos estar perdendo um eventual controle de qualidade ao gerarmos os `alternatives` mas ganharíamos tempo de processamento uma vez que não seria necessário gerar novas imagens.

Sobre os formatos de imagens eu acho que é o momento de utilizarmos padrões universais (PNG, JPEG), eles garantem imagens de qualidade e menores em `bytes`  se compararmos ao `tiff`, o material [1] tem informações bem pertinentes sobre otimização e uso de imagens na web. 

### Anexo
[[1] - Otimizando imagens para Web by Google](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization)
[[2] - Palestra sobre WebP](https://www.youtube.com/watch?v=pS8udLMOOaE)

**Comment by gustavofonseca** [comment]
> @gustavofonseca concordo com @specific-use="scielo-web" somente se servir para scielo, mas não seria o caso de ser "web" ou "web-only" apenas? o que a nossa web seria diferente das demais?
> Também acho que o content-type não precisa de ser scielo-, pois 50x50 acho que universal.

Eu coloquei `scielo` pensando em deixar claro que foi produzido por nós para ser utilizado por nós. Sinalizar de alguma forma que não foi produzido pelo autor.

**Comment by joffilyfe** [comment]
@gustavofonseca @robertatakenaka @patymori vocês concordam que a utilização do prefixo `scielo-` para o `specific-use` nos da mais contexto/controle sobre a utilização dos alternatives? 

Acredito que isso pode evitar eventuais problemas sobre os formatos, qualidade, dimensões, fps e tamanho em bytes para imagens/vídeos/etc. Mesmo que isso represente uma redundância de `alternatives` o preço a ser pago, na minha opinião, compensa.

**Comment by patymori** [comment]
> * [ ]  Discutir a interface de linha de comando adotada para o packtools;
>   
>   * ex: `comando pacote_sps.zip --asset-size=1024x960 860x540 250x100`
>   * ex: `comando pacote_sps.zip --asset-size-optimizer 3x`(teriamos algo como a imagem original e 3 versões reduzidas proporcionalmente)

Analisando agora, não sei se faz sentido informar em um mesmo pacote SPS os mesmos tamanhos para todas as imagens, tendo em vista que cada imagem de cada um dos artigos pode ter tamanhos completamente diferentes. Talvez faça mais sentido passar diferentes proporções diferentes da imagem, como:
* `comando pacote_sps.zip --asset-resize=0.8 0.5 0.3`
Onde cada um dos valores é a porcentagem do tamanho original, entre 0.01 e 1.0, que será aplicado para recalcular a altura e a largura, mantendo a proporção de cada uma das imagens.

@gustavofonseca @joffilyfe

**Comment by joffilyfe** [comment]
> > * [ ]   Discutir a interface de linha de comando adotada para o packtools;
> >   
> >   * ex: `comando pacote_sps.zip --asset-size=1024x960 860x540 250x100`
> >   * ex: `comando pacote_sps.zip --asset-size-optimizer 3x`(teriamos algo como a imagem original e 3 versões reduzidas proporcionalmente)
> 
> Analisando agora, não sei se faz sentido informar em um mesmo pacote SPS os mesmos tamanhos para todas as imagens, tendo em vista que cada imagem de cada um dos artigos pode ter tamanhos completamente diferentes. Talvez faça mais sentido passar diferentes proporções diferentes da imagem, como:
> 
>     * `comando pacote_sps.zip --asset-resize=0.8 0.5 0.3`
>       Onde cada um dos valores é a porcentagem do tamanho original, entre 0.01 e 1.0, que será aplicado para recalcular a altura e a largura, mantendo a proporção de cada uma das imagens.
> 
> 
> @gustavofonseca @joffilyfe

Eu acredito que nesse primeiro momento não é necessário redimensionar as imagens. Por enquanto nós precisamos transformar as imagens `TIF` em `PNG` para que o site continue operando.

Em um segundo momento, quando estivermos preparados para dar um passo mais largo, poderíamos implementar o redimensionar com foco ou não no site. Para o site por exemplo poderíamos usar o método  [thumbnail](https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#create-thumbnails) do Pillow e também o ratio como você sugere, acho que ficaria `helps`.

**Comment by gustavofonseca** [comment]
Estou de acordo com @joffilyfe no comentário acima.
