### ISSUE TITLE
Validar tag <institution content-type="normalized"> para normalização de instituições

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#22]
Validar tag <institution content-type="normalized"> para normalização de instituições.
O Packtools apresenta o seguinte erro para arquivos .xml com essa informação:

![normalizeeed](https://cloud.githubusercontent.com/assets/4397365/4681321/fbfe6912-5611-11e4-918c-f01883407903.jpg)

Arquivo disponível em:
Y:\SciELO_team\XML_PMC\Tickets-Packtools\22

**Comment by gustavofonseca** [comment]
Feito.
