### ISSUE TITLE
Atributo page-count do elemento counts não esta sendo validado pelo Style Checker.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/packtools#24]
O elemento page-count é obrigatório, entretanto o StyleChecker não indica isso quando o elemento não esta presente no XML.

Exemplo de xml: https://gist.github.com/fabiobatalha/6a94a935032d1e6ed371

**Comment by gustavofonseca** [comment]
@fabiobatalha, sei que faz tempo.. mas consegue arranjar o XML que apresenta o erro? O link para o gist não está funcionando

**Comment by fabiobatalha** [comment]
@gustavofonseca vou ter que gerar um XML, não sei pq o gist sumiu.

**Comment by fabiobatalha** [comment]
@gustavofonseca 

https://gist.github.com/fabiobatalha/c49f3510e516bca8d819

A documentação diz que na ausência de valores o elemento de contagem deve ser inserido com o atributo @count=0.

```
No caso de o documento não apresentar alguns dos elementos contabilizados, o valor dos respectivos atributos @count deve ser 0. e.g. <equation-count count="0"/>.
```

**Comment by fabiobatalha** [comment]
Para os demais elementos de contagem o StyleChecker esta validando corretamente.

**Comment by gustavofonseca** [comment]
ok, estou olhando. Valeu!
