### ISSUE TITLE
Alterar o HTML do artigo para conter tags image ao invés de imagens como background.

### ISSUE THREAD

**Issue by gitnnolabs** [scieloorg/packtools#270]
### Descrição da tarefa
Considerando a seguinte alteração de exibição das imagens por conta de preservação digital explicada no PR: https://github.com/scieloorg/opac/pull/2035 do OPAC. 

Faz-se necessário alterar o packtools para gerar uma tag **img** ao invés de **background-image**

As linhas de alteração são: 

https://github.com/scieloorg/packtools/blob/1f720c3d1cad00359a51a9b6e058a401c24746d6/packtools/catalogs/htmlgenerator/v2.0/article-text-fig.xsl#L31
https://github.com/scieloorg/packtools/blob/1f720c3d1cad00359a51a9b6e058a401c24746d6/tests/test_htmlgenerator.py#L712

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Realizando essa atividade.
