### ISSUE TITLE
Existência de <label> em <sec> não está sendo validado pelo Style Checker

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#28]
Conforme [nota para `<sec>` na SPS-1.1](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.1-branch/tagset.html#elemento-sec) a o atributo `<label>` não deve ser permitido.

    Não inserir a tag `<label>` para `<sec>`

Se possível seria ótimo que o renderizador entendesse o elemento `<label>`... ;-)

```xml
<sec id="sec4" sec-type="methods">
<label>4</label><title>Metodologia</title>
```

**Comment by gustavofonseca** [comment]
Boa, grato!

**Comment by gustavofonseca** [comment]
@lpanebr, esse ticket além de reportar uma não conformidade do stylechecker em relação a especificação, também sugere uma mudança na especificação SciELO PS. Entendi corretamente?

**Comment by lpanebr** [comment]
Sim @gustavofonseca, era isso sim, mas não se incomode. Eu já ajustei meu export para fazer merge dos label e title dentro dos sec. ;-)
