### ISSUE TITLE
label dentro de disp-formula perde-se e não aparece na página em HTML

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#29]
No PDF as equações tradicionalmente aparecem com o label numérico alinhado à direta, como ilustrado na Figura 1.

![image](https://cloud.githubusercontent.com/assets/129185/6193274/ac1eeeac-b3a0-11e4-99fe-0015db2de87f.png)
**Figura 1.** Imagem ilustrando uma equação no PDF

Essa estrutura é representada de forma valida no XML, conforme trecho destacado abaixo:

```xml
<p>Suponha que os escores das categorias de um item <italic>i</italic> são arranjados em ordem 
do menor para o maior e denotados por <italic>k</italic>=0;1;...; <italic>m<sub>i</sub></italic>, 
em que <italic>m<sub>i</sub></italic>+1 é o número de categorias do i-ésimo item. 
A probabilidade de um indivíduo <italic>j</italic> escolher uma particular categoria de resposta 
ou outra mais alta do item <italic>i</italic> pode ser dada por uma extensão do Modelo Logístico Unidimensional de 
Dois Parâmetros (MLU2) (<xref ref-type="bibr" rid="B001">ANDRADE; TAVARES; VALLE, 2000</xref>), 
conforme a <xref ref-type="disp-formula" rid="e01">Equação 1</xref>:
<disp-formula id="e01">
  <mml:math id="m1"> ... código equação suprimido para leitura ... </mml:math>
  <label>(1)</label>
</disp-formula>
</p>
```
Entretando o artigo no site SciELO não exibe o label (Figura 2). Ao consultar a [SPS](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.1-branch/tagset.html#elemento-disp-formula) observamos que não há documentação acerca do uso de label para equações.

![image](https://cloud.githubusercontent.com/assets/129185/6193257/849a722a-b3a0-11e4-9cfc-7ddaefff289d.png)
**Figura 2.** Equação no site SciELO sem o label.

Uma alternativa seria inserir o número da equação como sendo parte da própria equação. Entretanto seria ideal se a conversão para HTML pudesse resolver isso de forma melhor pois inserir o label na própria equação é uma solução bastante pobre.

**Comment by gustavofonseca** [comment]
@robertatakenaka, trata-se de um problema no site SciELO?

**Comment by leticiaquino** [comment]
@gustavofonseca e @lpanebr bom dia!
esse é um problema no site SciELO e não uma questão de validação. O tícket já havia sido criado no diretório correto em 13/02. De qualquer forma vou relacionar esse tícket ao outro.

**Comment by gustavofonseca** [comment]
@leticiaquino legal. Estou fechando esse ticket.

**Comment by lpanebr** [comment]
Obrigado. Qual é o repositório correto? Posso reportar outras coisas lá
diretamente.

Em 9h54 Qui, 19/02/2015, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
Repositório do site SciELO: https://github.com/scieloorg/Web/ <https://github.com/scieloorg/Web/>
Pode abrir tickets diretamente lá, ou encaminhar dúvidas para a lista scielo-dev

**Comment by lpanebr** [comment]
Obrigado!
