### ISSUE TITLE
Bug na validação de page-count do Style Checker

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#31]
Oi Gente,

Alguns periódicos usam as páginas do Editorial prefixadas (exemplo: E1) e isso gera erro na validação do `/article/front/article-meta/counts/page-count` pois fpage e lpage não são inteiros.[1]

O erro está na linha [455](https://github.com/scieloorg/packtools/blob/master/packtools/catalogs/scielo-style-1.1.sch#L455).

A solução (para PREFIXOS) seria considerar apenas os números à direita dos elementos `<fpage>E1</fpage>` e `<lpage>E1</lpage>`.

hmmmm...  temos também os SUFIXOS... embora mais raros. Talvez a solução mais genérica seja capturar apenas o número mesmo, descartando eventuais prefixos e sufixos:

```perl
 [^\d]*(\d+)[^\d]*
```

O trecho relevante do XML:

```xml
  <front>
    <article-meta>
[...]
      <pub-date pub-type="epub-ppub">
        <season>Jan-Feb</season>
        <year>2015</year>
      </pub-date>
      <volume>25</volume>
      <issue>1</issue>
      <fpage>E1</fpage>
      <lpage>E1</lpage>
      <counts>
        <fig-count count="0"/>
        <table-count count="0"/>
        <equation-count count="0"/>
        <ref-count count="0"/>
        <page-count count="1"/>
      </counts>
    </article-meta>
  </front>
```

[1] Exemplo de saída com erro `Element 'counts': Missing element or wrong value in page-count.`
![image](https://cloud.githubusercontent.com/assets/129185/6574982/1cce2642-c709-11e4-81e9-aa6ac5804c89.png)

**Comment by gustavofonseca** [comment]
Luciano, grato por reportar o problema. Você identificou apenas em editoriais?

**Comment by lpanebr** [comment]
De nada Gustavo.
O problema ocorre em artigos também.

**Comment by gustavofonseca** [comment]
Na realidade só é possível checar automaticamente o valor de *page-count* quando *fpage* e *lpage* são dígitos.
