### ISSUE TITLE
Figura suplementar de um artigo não aparece

### ISSUE THREAD

**Issue by tainacarneiro** [scieloorg/packtools#334]
### Descrição do problema

Figure S4 de um artigo da PAZ v62 lote 0622 (e202262039) não aparece. 

O artigo é "Small mammals and microhabitat selection in forest fragments in the transition zone between Atlantic Forest and Pampa biome".

A figura aparece na área de material suplementar, após as referências bibliográficas.

Mas está OK em [homolog](http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0031-10492022000100239&lng=en&nrm=iso&tlng=en) 
e OLD. 
NEW: https://www.scielo.br/j/paz/a/7pCNG8sjn6YBYrvwv4Pywpn/?lang=en#ModalFigf4 
OLD: https://old.scielo.br/scielo.php?script=sci_arttext&pid=S0031-10492022000100239&lng=en&nrm=iso&tlng=en

### Anexos
[1807-0205-paz-62-e202262039.zip](https://github.com/scieloorg/packtools/files/9779403/1807-0205-paz-62-e202262039.zip)

**Comment by tainacarneiro** [comment]
![1807-0205-paz-62-e202262039-gf4](https://user-images.githubusercontent.com/85230598/195673300-5108f0af-d514-452f-83b8-96b163c685c4.jpg)

**Comment by robertatakenaka** [comment]
@tainacarneiro foi resolvido com reproc, confere?
