### ISSUE TITLE
Garantir que todas as referências estejam citadas no texto.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#34]
Para qualquer valor ``a = ref/@id``, deve haver um ou mais ``b = body//xref[ref-type="bibr"]/rid`` onde ``a == b``.

**Comment by lpanebr** [comment]
UIA, ontem implantei isso no meu script python que checa coisas que o style
checker não checa!

Agora o style checker vai verificar isso?

Em qui, 26 de mar de 2015 11:47, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
Ainda preciso avaliar direito, mas a idéia é implementar essa funcionalidade sim.

**Comment by lpanebr** [comment]
Legal.

Outro dia eu estava pensando: não seria legal e útil se o style checker
aceitasse plugins?

Talvez até facilitasse a implantação de novas checagens para vocês...

Poderiam ser scripts python que tomassem o xml, os parâmetros do próprio
style checker e outros* e retornassem um objeto JSON pronto para usar no
output.

* outros parâmetros poderiam vir da própria linha de comando (não sei se da
pra ter parâmetros não esperados. Talvez o style checker possa registrar os
parâmetros dos plugins...) e do arquivo de config dos plugins...

Enfim... Falar é fácil....

Abraço!

Em qui, 26 de mar de 2015 12:36, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
A idéia é interessante. Pode abrir um ticket para isso citando casos de uso para eu ter como referência?

**Comment by lpanebr** [comment]
Vou abrir.
:-D

Em qui, 26 de mar de 2015 14:44, Gustavo Fonseca <notifications@github.com>
escreveu:

> A idéia é interessante. Pode abrir um ticket para isso citando casos de
> uso para eu ter como referência?
>
>

**Comment by lpanebr** [comment]
Ticket criado!

https://github.com/scieloorg/packtools/issues/35





Atenciosamente,

*Luciano Panepucci*
Cofundador e Diretor de Tecnologia

+55 (16) 3307-2068
+55 (16) 991 728 681
skype: lpanebr


soluções para o universo acadêmico

<http://www.facebook.com/editoracubo>  <http://twitter.com/editoracubo>
<http://www.linkedin.com/company/editora-cubo>
<http://gplus.to/editoracubo>  <http://blog.editoracubo.com.br/>

Rua Marechal Deodoro 2709
13560-201 São Carlos - SP
www.editoracubo.com.br

--------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

--------
Notes to myself:
Falta de tempo é desculpa daqueles que perdem tempo por falta de métodos.
[Albert Einstein]

Helpdesk:
http://helpdesk.editoracubo.com.br


2015-03-26 15:42 GMT-03:00 Luciano Panepucci <lpanebr@gmail.com>:

> Vou abrir.
> :-D
>
> Em qui, 26 de mar de 2015 14:44, Gustavo Fonseca <notifications@github.com>
> escreveu:
>
>> A idéia é interessante. Pode abrir um ticket para isso citando casos de
>> uso para eu ter como referência?
>>
>>

**Comment by gustavofonseca** [comment]
O caso de uso de citação com intervalo invalida esse ticket.
```xml
<xref ref-type="bibr" rid="B001"><sup>1</sup></xref><sup>-</sup><xref ref-type="bibr" rid="B003"><sup>3</sup></xref>
```

Referência: https://groups.google.com/d/msg/scielo-xml/q0jyI0yLnAc/Qkt0SXRYbkgJ

**Comment by lpanebr** [comment]
Mas inválida apenas para alguns casos.
É muito comum a utilização de citação do tipo autor data onde não há
intervalos e todas as referências precisam estar citadas.

Quando as referências possuem um label a validação seria pertinente e útil.

eu utilizo o seguinte algoritmo no meu sistema:

Se a quantidade de citações distintas no corpo for diferente da quantidade
de referências no back temos um problema. Nesse caso faço a diferença entre
os arrays e exibo os ids não citados.

Isso me ajuda muito pois as meninas do scielo sempre reclamam quando o xml
não possui as referências citadas.

Luciano
Desculpe os erros de digitação e falta de pontuação este meio foi meio que
ditado para o celular

Em qua, 15 de abr de 2015 11:21, Gustavo Fonseca <notifications@github.com>
escreveu:
