### ISSUE TITLE
Ideia para sistema de plugins

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#35]
Não seria legal e útil se o style checker aceitasse plugins?

Talvez até facilitasse a implantação de novas validações pela própria equipe pois estariam desacopladas do código principal..

Esses plugins poderiam ser scripts python que tomassem o xml, os parâmetros do próprio style checker e outros* e retornassem um objeto JSON pronto para usar no output.

* outros parâmetros poderiam vir da própria linha de comando e do arquivo de config..

O style checker poderia registrar os plugins e seus parâmetros a partir do arquivo de config...

**Config plugins:**

```javascript
{
    "plugins": {
        "check_issn": {
            "help": "Uses the journal-id and checks if the filename starts with the expected issn.",
            "prefix": "ec", //para evitar conflitos ao registrar os parâmetros..
            "path": "/home/lpanebr/ec-stylechecker/plugins/", //if they are not on the expected folder
            "script": "ec-check-ref-citations.py",
            "parameters": [ 
            	{ // some structure that could be used by the parser.add_argument syntax while registering the plugin..
            		"param": "-issn",
            		"help": "Which ISSN to use? epub or ppub.",
            		"required": True
            	},
            ]
        },
        "check_reference_citations": {
            "help": "Checks if all references have a corresponding xref citation.",
            "prefix": "ec", //para evitar conflitos ao registrar os parâmetros..
            "path": "/home/lpanebr/ec-stylechecker/plugins/", //if they are not on the expected folder
            "script": "ec-check-ref-citations.py",
            "parameters": null // if no param are nedded..
        },
    }
}
```

Enfim... Falar é fácil....

**Comment by gustavofonseca** [comment]
Com certeza seria legal ter essa funcionalidade, mas não estou convencido do custo-benefício. Por hora foi implementada a capacidade de executar uma validação extra, por meio da opção **--extrasch** no stylechecker e também por vias programáticas [34ed79f86802ea06bca148ef8485e8d4a7b6627b]. Imagino que essa implementação já abra algumas possibilidades de automação.

Vou fechar esse ticket, e caso um dia a idéia de uma arquitetura de plugins se mostre mais interessante a gente reabre. Valeu!

**Comment by lpanebr** [comment]
Essa possibilidade de um schematron externo já é incrível! Espero poder
testar quando voltar de férias...

On Tue, Jun 30, 2015 at 11:55 AM Gustavo Fonseca <notifications@github.com>
wrote:

> Com certeza seria legal ter essa funcionalidade, mas não estou convencido
> do custo-benefício. Por hora foi implementada a capacidade de executar uma
> validação extra, por meio da opção *--extrasch* no stylechecker e também
> por vias programáticas [34ed79f
> <https://github.com/scieloorg/packtools/commit/34ed79f86802ea06bca148ef8485e8d4a7b6627b>].
> Imagino que essa implementação já abra algumas possibilidades de automação.
>
> Vou fechar esse ticket, e caso um dia a idéia de uma arquitetura de
> plugins se mostre mais interessante a gente reabre. Valeu!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/packtools/issues/35#issuecomment-117216713>.
>
-- 

att.
Luciano Panepucci

(enviado do celular)
