### ISSUE TITLE
Erro de DTD para pub-id em ref

### ISSUE THREAD

**Issue by javani** [scieloorg/packtools#36]
Apresenta erro de DTD no elemento pub-id em element-citation.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.1-branch/tagset.html#pub-id

**Comment by gustavofonseca** [comment]
Pode, por gentileza, colar aqui a mensagem de erro?

**Comment by gustavofonseca** [comment]
@javani vou fechar esse ticket por falta de informação. Caso necessário, peço que reabra esse ticket acrescentando detalhes para que eu possa identificar o erro.
