### ISSUE TITLE
Avaliar possibilidade de outra codificação para <, > e &

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#38]
Bom dia,

Atualmente a SPS exige que as seguintes codificações para os 3 caracteres abaixo:

* `&lt;` para `<`
* `&gt;` para `>`
* `&amp;` para `&`

Gostaria de solicitar que por favor avaliassem a possibilidade de aceitar **também** as codificações abaixo:

* `&#x003C;` para `<`
* `&#x003E;` para `>`
* `&#x0026;` para `&`

Creio que ambas são seguras, resultam em HTML válido e podem co-existir..

obrigado,

Luciano

**Comment by gustavofonseca** [comment]
@lpanebr, as codificações sugeridas já são válidas para o packtools e eu não encontrei, na documentação da SciELO PS 1.1, o local onde essa restrição é explicitada. Consegue me passar mais detalhes?

**Comment by lpanebr** [comment]
Ou Gustavo,

Acredito que isso não esteja explícito na documentação entretanto as
meninas do scielo sempre devolvem os pacotes solicitando essa correção.

Veja a orientação semelhante da Roberta no grupo:
https://groups.google.com/forum/m/?utm_source=digest&utm_medium=email/#!topic/scielo-xml/lJhspUw0uUg

Em qui, 2 de abr de 2015 10:26, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
Luciano, vou verificar os motivos da recomendação.

**Comment by gustavofonseca** [comment]
Outra coisa, qual o caso de uso em que é preferível utilizar referências numéricas ao invés de referências de entidade?

**Comment by lpanebr** [comment]
Oi Gustavo,

Que eu saiba não há algum caso de uso em que seja vantajoso usar um nem o
outro.. nem posso dizer que o motivo seja muito nobre... Não sei se iria
beneficiar outros prestadores. Pode pareber besteira mas é que eu
simplesmente não consegui fazer meu export dar saída usando as as entidades
e só por isso preciso rodar um post-process ... :-/

Fique a vontade para dropar o ticket.

Obrigado pelo retorno!

**Comment by gustavofonseca** [comment]
Tarefa movida para https://github.com/scieloorg/scielo_publishing_schema/issues/76
