### ISSUE TITLE
Packtools - link de licença apresenta erro se não existir uma barra final

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#39]
O programa apresenta erro em licença quando o link não apresenta uma barra final. Veja:

![licenca-barra](https://cloud.githubusercontent.com/assets/4397365/7005074/de181de8-dc4a-11e4-9474-53414c78383a.jpg)

![licenca-url](https://cloud.githubusercontent.com/assets/4397365/7005094/25faf298-dc4b-11e4-8af6-f49bd2eb73e0.jpg)

Se inserir a barra, o arquivo é validado:

![url-barra](https://cloud.githubusercontent.com/assets/4397365/7005108/572658a8-dc4b-11e4-860a-9f8008c521c7.jpg)

Verificar a possibilidade de ignorar o uso da barra final.

**Comment by gustavofonseca** [comment]
Sim. Esse erro foi corrigido apenas para documentos sps-1.2. Vou aplicar a correção para sps-1.1.

**Comment by leticiaquino** [comment]
@gustavofonseca na versão 1.2 o erro também ocorre. Veja:
![gustavo-error](https://cloud.githubusercontent.com/assets/4397365/7030876/2835c0bc-dd3e-11e4-87cb-9f9055a8ca5d.jpg)

**Comment by gustavofonseca** [comment]
Ops, agora a coisa ficou séria rs

**Comment by gustavofonseca** [comment]
Realmente… a correção que fiz foi para suportar tanto scheme *http* quanto *https*, e não para a barra final.

**Comment by leticiaquino** [comment]
@gustavofonseca ahá
