### ISSUE TITLE
Avaliar o uso dos elementos <copyright-year> e  <copyright-holder> em <permission>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#40]
Verificar a possibilidade de uso dos elementos ```<copyright-year>``` e  ```<copyright-holder>``` em ```<permission>``` de acordo com as recomendações da JATS4R:

https://github.com/JATS4R/elements/wiki/Permissions

**Comment by gustavofonseca** [comment]
Relacionado ao #80
