### ISSUE TITLE
Criar módulo para gerar o formato do protocolo OAI-PMH de "GetRecord"

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/packtools#406]
### Descrição da tarefa
Criar módulo para gerar o formato do protocolo OAI-PMH para os MetadataPrefix a partir de um artigo (XML SciELO):

### Subtarefas
- [x] oai_dc
- [x] oai_dc_agris
- [ ] oai_dc_openaire

### Referências
- Documentação do **oai_dc**: http://www.openarchives.org/OAI/openarchivesprotocol.html
- OAI do SciELO Chile https://www.scielo.cl/oai/ (exemplos reais)
- Lista de **identificadores** (**identifier** são necessários para GetRecord) https://www.scielo.cl/oai/scielo-oai.php?verb=ListIdentifiers&metadataPrefix=oai_dc&from=2023-01-01
- Exemplo do verbo GetRecord: https://www.scielo.cl/oai/scielo-oai.php?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:scielo:S0718-71812019000100243

### Notas
- Observe a questão de namespace: https://github.com/scieloorg/articles_meta/blob/75ebb158d0ca801f3495a80ec7352c8393eda541/articlemeta/export_rsps.py#L350
-

**Comment by lpanebr** [comment]
> - Exemplo do verbo GetRecord: https://www.scielo.cl/oai/scielo-oai.php?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:scielo:S0718-71812019000100243

Não sei se fiz algo errado, acho que foi azar, mas justo URL do `dc:identifier` desse GetRecord está retornando `HTTP ERROR 500`.

```xml
<dc:identifier>
http://www.scielo.cl/scielo.php?script=sci_arttext&amp;pid=S0718-71812019000100243
</dc:identifier>
```
