### ISSUE TITLE
Gerar o XML do PubMed Central (Parte 1)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/packtools#436]
### Descrição da tarefa
Gerar o XML do PubMed Central (PMC) / similar a JATS

Validadores
https://www.ncbi.nlm.nih.gov/pmc/tools/stylechecker/
https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker/

Consultar a documentação https://www.ncbi.nlm.nih.gov/pmc/pub/filespec/, para verificar as diferenças

Principais diferenças:
<img width="657" alt="Captura de Tela 2023-07-03 às 16 33 07" src="https://github.com/scieloorg/packtools/assets/505143/752791e2-0aad-4a5c-8495-15f5f95ddd7b">
<img width="513" alt="Captura de Tela 2023-07-03 às 16 33 20" src="https://github.com/scieloorg/packtools/assets/505143/79b60a10-3947-4ae9-8553-987895d7baae">
<img width="683" alt="Captura de Tela 2023-07-03 às 16 33 42" src="https://github.com/scieloorg/packtools/assets/505143/975d7284-e12f-4a06-9628-39b4d4026dd0">
<img width="502" alt="Captura de Tela 2023-07-03 às 16 34 08" src="https://github.com/scieloorg/packtools/assets/505143/1c4cb135-1040-40fb-ada4-6e36a091f350">

**Comment by RPostalli** [comment]
@robertatakenaka Não tem mais diferenças entre pub-date SciELO X PMC. Tinha antigamente, por favor desconsiderar essa informação, o [Guia interno](https://documentacao.scielo.org/books/guias-do-nucleo-de-publicacao/page/pmc) já foi alterado.
