### ISSUE TITLE
[htmlgenerator] tests: adicionar tests para os outros tipos de produtos

### ISSUE THREAD

**Issue by jfunez** [scieloorg/packtools#46]
atualmente só tem um test para o <product> do tipo: `book` mas existem outro como:
- article
- chapter
- other
- software

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#product

**Comment by gustavofonseca** [comment]
Marcado como inválido pois o gerador de HTML foi reimplementado.
