### ISSUE TITLE
Elementos mínimos por tipo de referência

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#48]
**element-citation[@publication-type="book"]:** 1) Não pode constar: *article-title*, 2) Pode constar: *chapter-title*, 3) Deve constar: *source* e *year*.
**element-citation[@publication-type="journal"]:** 1) Não pode constar: *chapter-title*, 2) Pode constar: *article-title*, 3) Deve constar: *source* e *year*.
**element-citation[@publication-type="confproc"]:** 1) Deve constar: *conf-name*. 
**element-citation[@publication-type="webpage"]:** 1) Deve constar *ext-link[ext-link-type="uri"]* e *date-in-citation[@content-type="access-date"]*.

----
Atualização:
A ausência dos elementos marcados como **Deve constar** ou a ocorrência dos marcados como **Não pode constar** deve resultar em erro de validação. Esse ticket é ortogonal ao https://github.com/scieloorg/scielo_publishing_schema/issues/64.

**Comment by gustavofonseca** [comment]
Dúvida: No guia, a caixa **importante**[1] diz que para o tipo **journal** há 4 elementos obrigatórios: *article-title*, *surname*, *source* e *year*. Quem está certo? (alô @leticiaquino)

[1]http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#element-citation

**Comment by leticiaquino** [comment]
alô @gustavofonseca! quando foi inserido essa caixa "importante" eu me baseei no seguinte tícket: https://github.com/scieloorg/scielo_publishing_schema/issues/64.

O problema é que se restringirmos a validação tambpem por "person-group", acredito que pouca coisa será validada.

**Comment by gustavofonseca** [comment]
vc acha que a ausência do *person-group//surname* deve resultar apenas na necessidade do atributo *@specific-use=”display-only”*?

**Comment by leticiaquino** [comment]
Talvez possamos falar mais sobre isso, pois eu concordo com a inserção do
display-only para quando não existir o person-group//surname, pensando no
trabalho que está sendo desenvolvido pelo Jamil (que você comentou)..

Por outro lado, eu acredito que se o packtools "barrar" arquivos que não
apresentam o person-group//surname a correção será bastante complexa..


2015-05-13 16:42 GMT-03:00 Gustavo Fonseca <notifications@github.com>:

> vc acha que a ausência do *person-group//surname* deve resultar apenas na
> necessidade do atributo *@specific-use=”display-only”*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/packtools/issues/48#issuecomment-101791198>.
>



-- 
Letícia Aquino
Unidade SciELO
leticia.aquino@scielo.org
www.scielo.org
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
www.scielo.org | www.scielo.br

**Comment by leticiaquino** [comment]
@gustavofonseca As validações feitas pelo converter são apenas para conferir se o tipo de referência está correto.

**Comment by gustavofonseca** [comment]
@leticiaquino hm estranho pensar que o converter assumiu responsabilidades de validação de conteúdo. Mas enfim, vou implementar essas validações no packtools.

**Comment by leticiaquino** [comment]
@gustavofonseca hey..
ficou da seguinte forma:

**Obrigatório**
"journal: article-title', 'person-group', 'year', 'source'
'book': 'year', 'source'
confproc: 'conf-name', 'source', 'year'
thesis: 'comment', 'source', 'year'
webpage: 'ext-link', 'date-in-citation[@content-type="access-date"]', 'source' (nota: date-in-citation[@content-type="update"] vale também)

**Elementos NÃO permitidos:**
'journal' = ['chapter-title']
'book' = ['article-title']
'webpage' = ['volume', 'issue', 'fpage']"

**Comment by leticiaquino** [comment]
Se não existir um desses elementos que constam no "obrigatório", deve ser inserido um "display-only"

**Comment by gustavofonseca** [comment]
Eu acho que o uso do **@specific-use="display-only"** está relacionado com uma nuance diferente. Exemplo: uma referência do tipo *webpage* que não apresenta *ext-link* deve ser um erro, e não uma versão apenas para exibição. O **@specific-use="display-only"** está mais relacionado com metadados que utilizamos internamente para análises e métricas, e esse ticket está mais para a "boa formação" das referências por tipo. Ou estou enganado? rs

**Comment by robertatakenaka** [comment]
@gustavofonseca : sim, uma referência do tipo webpage que não apresenta ext-link deve ser um erro. Cabe ao provedor do XML verificar se o ref é mesmo webpage, mas se sim e não tem link (o que seria bem estranho neste caso, mas imagine um caso ilustrativo), ele deveria informar @specific-use="display-only" já que a referência é incompleta.

É por isso, que testo o mínimo. Confproc não pode ser sem conf-name, webpage sem link, etc. Porque estaria bem certo que o tipo estaria errado.

**Comment by gustavofonseca** [comment]
@robertatakenaka eu entendo mas penso que essas regras estão fora das responsabilidades do packtools. O stylechecker do packtools figura não o papel de um cara que levanta bandeiras de possíveis erros que podem ser silenciados com algo como o atributo **@specific-type="display-only"**. 

O stylechecker tem um comportamento binário totalmente relacionado à validade e boa-formação da estrutura do XML. 

Respeitando a responsabilidade do stylechecker, no exemplo que vc apresentou da referência para webpage sem ext-link deve ser um erro. Algo como, em um tabuleiro com espaços geométricos, tentar encaixar um quadrado no espaço de um círculo.

**Comment by gustavofonseca** [comment]
Esse ticket está sendo fechado sem ter sido realizado por conta da dubiedade envolvendo o requisito.
