### ISSUE TITLE
Elementos que não devem constar em determinados tipos de referência.

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#50]
Book
`<article-title>`, `<conf-date>`, `<conf-loc>`, `<conf-name>`, `<conf-num>`, `<conf-sponsor>`, `<conf-theme>`, `<conference>`; *`<patent>`;

Journal
`<chapter-title>`, `<conf-date>`, `<conf-loc>`, `<conf-name>`, `<conf-num>`, `<conf-sponsor>`, `<conf-theme>`, `<conference>`; *`<patent>`;

Thesis
`<article-title>`, `<conf-date>`, `<conf-loc>`, `<conf-name>`, `<conf-num>`, `<conf-sponsor>`, `<conf-theme>`, `<conference>`; *`<patent>`;

Conference
~~`<article-title>`;~~ `<chapter-title>`; `<patent>`;

Webpage
`<article-title>`, `<chapter-title>`

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/toc.html

**Comment by leticiaquino** [comment]
Webpage
```<article-title>```, ```<chapter-title>```, ```<conf-date>```, ```<conf-loc>```, ```<conf-name>```, ```<conf-num>```, ```<conf-sponsor>```, ```<conf-theme>```, ```<conference>```; *```<patent>```

**Comment by leticiaquino** [comment]
@gustavofonseca em Conference a Suely percebeu que é possível utilizar o ```<article>```. Veja a resposta abaixo:

```code
Bom dia todos,

Letícia, existem casos de "conf-proc" em que <article-title> pode estar presente.

Quando na conferencia  é apresentado somente uma parte de uma obra ela é marcada com <article-title> e a obra em <source>.

Então, junto aos elementos essenciais sobre o "conf-proc" (<conf-name>,<conf-date>, <conf-loc>) <article-title> pode haver se constar um <source>.


Exemplos no link abaixo;

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/confpub2.html#d3e39741
```

**Comment by gustavofonseca** [comment]
Ok. Está começando ficar mais interessante =P

**Comment by leticiaquino** [comment]
@gustavofonseca @suelylc 

verifiquei que é possível sim ter uma conferência apenas com ```<aticle-title>``` sem o ```<source>```. Veja:
http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/citations/v3/confpub2.html#d3e36472

**Comment by suelylc** [comment]
Sim, realmente não tinha percebido esse exemplo....
Então, já que temos essas duas possibilidades article-title+source, somente article-title ou somente source a validação para "conf-proc" levará em conta somente os lementos essenciais para esse tipo. Certo?
Seria interessante acrescentar exemplos desses casos do guia...

**Comment by leticiaquino** [comment]
@suelylc Na verdade a validação será feita atraves dos elementos que não devem constar em cada tipo. Então nesse caso será considerado apenas ```<chapter-title>``` e ```<patent>```.

Seria interessante inserir um exemplo desse no guia.

**Comment by suelylc** [comment]
@leticiaquino Certo, ratificando, digo de colocarmos um exemplo para cada caso no guia  para a aplicação adquada dos elementos ```source``` e/ou ```article-titlie``` em "conf-proc" já que a presença ou não desses elementos não vai interferir na validação.

**Comment by gustavofonseca** [comment]
@leticiaquino e @suelylc, eu corrigi o texto que descreve os elementos proibidos para o referências do tipo **conferência**. Está certo agora?

Outra coisa, vocês estão considerando adicionar essas regras no guia da versão 1.2?

**Comment by leticiaquino** [comment]
@suelylc @gustavofonseca Olá Gustavo! Agora está correto.

Sim, podemos inserir essas regras em um tópico antes de apresentarmos os exemplos. Pode ser?

**Comment by gustavofonseca** [comment]
@leticiaquino pode ser.

**Comment by suelylc** [comment]
@gustavofonseca @leticiaquino  Letícia, os exemplos que serão inseridos já temos? Senão posso providenciar.

**Comment by leticiaquino** [comment]
@suelylc Suely, eu estava verificando com o @gustavofonseca ontem, a possibilidade de publicarmos aquele catálogo de casos de uso - Referência Bibliográfica. Acredito que com esse catálogo conseguimos minimizar as dúvidas sobre esse assunto e não poluimos tanto a documentação.

**Comment by suelylc** [comment]
Ok.

Em 27 de maio de 2015 11:13, Letícia Aquino <notifications@github.com>
escreveu:

> @suelylc <https://github.com/suelylc> Suely, eu estava verificando com o
> @gustavofonseca <https://github.com/gustavofonseca> ontem, a
> possibilidade de publicarmos aquele catálogo de casos de uso - Referência
> Bibliográfica. Acredito que com esse catálogo conseguimos minimizar as
> dúvidas sobre esse assunto e não poluimos tanto a documentação.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/packtools/issues/50#issuecomment-105926905>.
>



-- 
Atenciosamente,

Suely Lucena

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

<http://www.scielo15.org/>

*SciELO 15 anos*
http://www.scielo15.org

**Comment by javani** [comment]
@leticiaquino então faremos os comentários do catálogo de casos. Em webpage pode ter article-title. 
Veja o caso:
Food and Drug Administration (FDA). Natural Grocers® issues recall of Macadamia Nuts due to possible health risk. Recalls, Market Withdrawals, & Safety Alerts, 2015. http://www.fda.gov/Safety/Recalls/ucm448353.htm, acessado em 28/05/2015.

**Comment by gustavofonseca** [comment]
Por hora o validador não será responsável por validar a estrutura das referências com base no seu tipo. O ticket será marcado como "não realizado" e fechado.
