### ISSUE TITLE
Permitir schematron externo

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/packtools#55]
Pensando que as diferentes coleções SciELO poderão apresentar regras próprias, deve ser possível indicar um schematron externo a ser executado adicionalmente às validações padrão.

Exemplo de usos:

```
validator = XMLValidator(xml,  extra_sch=sch)
```

```
$ stylechecker --extrasch meu_schematron.sch meu_xml.xml
```

**Comment by lpanebr** [comment]
Que maravilha!

**Comment by gustavofonseca** [comment]
Fala @lpanebr! Você tem algum caso de uso para essa funcionalidade?

**Comment by lpanebr** [comment]
Oi Gustavo,
Não tenho nada pronto, mas gostaria de usar para fazer as validações
associadas, tipo:
Valores e tipos de ISSN
Prefixo DOI utilizado
Journal full and abbreviated name
Publisher
Etc

Em sex, 19 de jun de 2015 11:27, Gustavo Fonseca <notifications@github.com>
escreveu:

> Fala @lpanebr <https://github.com/lpanebr>! Você tem algum caso de uso
> para essa funcionalidade?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/packtools/issues/55#issuecomment-113530835>.
>
-- 

att.
Luciano Panepucci

(enviado do celular)

**Comment by gustavofonseca** [comment]
Sim, e vc consegue inclusive ter schematrons específicos para cada revista que produz, com um nível de especialização bem alto.

**Comment by lpanebr** [comment]
Pois é exatamente o que quero fazer! Se eu encontrasse um nerd hacker pra
contratar já teria feito tanta coisa...

Abraço

Em sex, 19 de jun de 2015 12:19, Gustavo Fonseca <notifications@github.com>
escreveu:

> Sim, e vc consegue inclusive ter schematrons específicos para cada revista
> que produz, com um nível de especialização bem alto.
>
> > On 19/06/2015, at 11:37, Luciano <notifications@github.com> wrote:
> >
> > Oi Gustavo,
> > Não tenho nada pronto, mas gostaria de usar para fazer as validações
> > associadas, tipo:
> > Valores e tipos de ISSN
> > Prefixo DOI utilizado
> > Journal full and abbreviated name
> > Publisher
> > Etc
> >
> > Em sex, 19 de jun de 2015 11:27, Gustavo Fonseca <
> notifications@github.com>
> > escreveu:
> >
> > > Fala @lpanebr <https://github.com/lpanebr>! Você tem algum caso de uso
> > > para essa funcionalidade?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/scieloorg/packtools/issues/55#issuecomment-113530835>.
> > >
> > --
> >
> > att.
> > Luciano Panepucci
> >
> > (enviado do celular)
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/scieloorg/packtools/issues/55#issuecomment-113533105>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/packtools/issues/55#issuecomment-113546481>.
>
-- 

att.
Luciano Panepucci

(enviado do celular)

**Comment by gustavofonseca** [comment]
:+1:
