### ISSUE TITLE
Atualizar Propriedade collab da Classe Authors para Gerar Textos de Múltiplos Colaboradores em Vez de Retornar um Único Valor.

### ISSUE THREAD

**Issue by samuelveigarangel** [scieloorg/packtools#559]
### Descrição do problema
Atualmente, a implementação da propriedade collab na classe Authors é projetada para retornar o texto do primeiro elemento <collab> encontrado no XML. No entanto, na estrutura dos documentos XML, pode haver casos conforme, documentado pela [Scielo Publishing Schema](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt-br/latest/tagset/elemento-collab.html?highlight=collab#elemento-collab-exemplo-3), em que mais de um elemento <collab> está presente.

**Comment by robertatakenaka** [comment]
@samuelveigarangel o PR #558 deve solucionar a questão
