### ISSUE TITLE
Não acusar erro para link de licença by-nc-nd

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/packtools#58]
Como já tínhamos revistas com esta licença 9by-nc-nd) e só documentamos este tipo de licença by-nc-nd somente no SPS 1.2 o Style Checker não deveria acusar erro para versões anteriores (1.1).

Devemos tomar este problema como um problema na documentação desde o início e não na versão 1.1, pois a mesma deveria suportar também este tipo de licença.

**Comment by gustavofonseca** [comment]
O packtools somente implementa as regras seguindo as versões da especificação. A versão 1.1 da especificação não prevê a licença BY-NC-ND.

**Comment by RPostalli** [comment]
Ok, mas a regra estava errada na versão 1.1. Neste caso temos que obrigar as revistas que já usavam a licença by-nc-nd entregarem XML's na versão 1.2 do SPS só por que não havíamos documentado algo que deveríamos?

Os prestadores estão reportando o erro e não podemos dizer que a licença é incorreta, mesmo que  com sprecif-use 1.1.

Como resolvemos este problema?

**Comment by gustavofonseca** [comment]
Não. Deveríamos abrir uma solicitação de mudança na SPS 1.1. Mas é importante lembrar que em setembro não serão mais aceitos xmls da versão 1.1.
