### ISSUE TITLE
Previewer não apresenta todos os dados iniciais do documento

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#64]
Verifiquei que o htmlgenerator não apresenta os seguintes dados:
- Seção (identificada em `<subject>`);
- Afiliações (em `<aff>` : utilizar conteúdo de `<institution content-type="original">`);
- Resumos (identificados em `<abstract>` e `<trans-abstract>`);
- DOI se repete;

Notei ainda que foi criado um campo "About the authors e um "Authors notes", entretanto há apenas a informação de correspondência. Evitar apresentar determinados campos quando não há dado;
O mesmo ocorre para informação de financiamento.

Exemplo:

![previewer](https://cloud.githubusercontent.com/assets/4397365/10524687/4167943e-7357-11e5-9c46-ed477715b42a.jpg)

**Comment by jfunez** [comment]
@leticiaquino pode me indicar o xml que esta usando? de qual versão de sps? (ou se for pre-sps)

- Seção (identificada em ``<subject>``);  :+1: a única informação da seção é o title por enquanto. (https://github.com/scieloorg/packtools/blob/html-generator/packtools/catalogs/htmlgenerator/root-html-1.2.xslt#L1079) mas qual seria o layout para este ``<subject> `` ? é mutuamente exclusivo o title e o subject?
- Afiliações (em <aff> : utilizar conteúdo de <institution content-type="original">); suspeito que o problema é o xml, pq para sps funciona (https://github.com/scieloorg/packtools/blob/html-generator/packtools/catalogs/htmlgenerator/root-html-1.2.xslt#L868)
- Resumos (identificados em ``<abstract>`` e ``<trans-abstract>``); se o xml é pre-sps pode não aparecer do jeito certo, mas no sps já aparece um abstract para cada versão (html) gerado. pode conferir nas imagens anexas.
- DOI se repete; **sim, o mockup do novo site foi definido assim** 
- Notei ainda que foi criado um campo "About the authors" e um "Authors notes", entretanto há apenas a informação de correspondência :+1: a informação exibida (correspondência) é a informação que a ferramenta conseguiu recuperar, vendo as imagens abaixo, seria possível mostrar uma informação semelhante para o xml que vc usou?
os títulos de esses campos, foi definido no mockup, para o novo site.
- Evitar apresentar determinados campos quando não há dado; O mesmo ocorre para informação de financiamento. :+1: concordo, só no sabemos até agora quais campos podem ficar vazio :)

seguem as imagens anexas do artigo: 0034-8910-rsp-48-2-0357 em português e inglês.
Grato pelo feedback!!!
Aguardo os comentários.

![screen shot 2015-10-15 at 16 36 23](https://cloud.githubusercontent.com/assets/805749/10525446/36503354-735b-11e5-847f-f34457bd22f6.png)


![screen shot 2015-10-15 at 16 36 13](https://cloud.githubusercontent.com/assets/805749/10525435/2dac179a-735b-11e5-927c-9bf1768b52f3.png)

**Comment by leticiaquino** [comment]
@jfunez o arquivo .xml que eu estava utilizando está na versão 1.2..
já tenho aqui um .xml na versão 1.3, mas ainda não comecei a verificação do previewer desse.

Eu enviei via e-mail o arquivo .xml que eu utilizei para você conferir meus apontamentos.


sobre seus comentários:

"Seção (identificada em <subject>); :+1: a única informação da seção é o title por enquanto. (https://github.com/scieloorg/packtools/blob/html-generator/packtools/catalogs/htmlgenerator/root-html-1.2.xslt#L1079) mas qual seria o layout para este <subject> ? é mutuamente exclusivo o title e o subject?"
Quando você diz "o tile e o subject" você está se referindo ao título do artigo? Se for isso, informo que a seção independe do título do artigo.

":+1: a informação exibida (correspondência) é a informação que a ferramenta conseguiu recuperar, vendo as imagens abaixo, seria possível mostrar uma informação semelhante para o xml que vc usou? os títulos de esses campos, foi definido no mockup, para o novo site." 
Isso quer dizer que uma vez que esses campos foram definidos eles irão aparecer no previewer independente se houver conteúdo?

**Comment by jfunez** [comment]
@leticiaquino 
sobre a informação que não aparece (prepara um café :coffee: que vem historia longa):

#### abstract e trans-abstract
Eu tinha visto que o abstract estava associado ao idioma (atributo lang)[1], mas pelo visto pode aparecer o tag sem atributo. Então tem vários cenários possíveis:

- processando uma tradução, e o a abstract esta em: ``sub-article[lang]/front-stub/abstract/[lang]``
- processando uma tradução, e o a abstract esta em: ``sub-article[lang]/front-stub/trans-abstract/[lang]``
- processando uma tradução, e o a abstract esta em: ``article/front/article-meta/trans-abstract[lang]/``
- nenhuma das anteriores e o abstract esta em: ``article/front/article-meta/abstract[@xml:lang=$article_lang]``

Além destes cenários (contemplados atualmente) teríamos que avaliar uma 3ra variável que seria a existência ou não do atributo [lang] no abstract (e trans-abstract).

:point_right: Consegue me dizer ser isso seriam todos os cenários possíveis?

#### subject
esta informação estava presente nas primeira versões do preview, mas foi removida. porque no mockup que temos como guia não aparece eu acho [2]. 

:point_right: Qual seria um bom lugar para mostrar no layout atual?

#### About the authors:
Esta informação é obtida das tags ``<aff>`` dentro de ``<article-meta>``[3]
E no caso do teu XML não tem nenhum. somente ``<aff>`` dentro de ``<contrib-group>``. 

:point_right: Existe algum jeito certo? ou ambos cenários são válidos?

#### Financiamento:
Pelo que eu fiz, eu só pego a tag: ``<funding-statement>`` que segundo a documentação:
> Representa os dados de financiamento exatamente como apresentado na nota de rodapé.

:point_right: quais campos deve mostrar no html? Adianta com incluir somente ``<funding-source>`` e no caso de ter varios ``<award-id>`` e ignorar o ``<funding-statement>``.

aguardo os comentários! 

[1] https://github.com/scieloorg/packtools/blob/master/tests/samples/0034-8910-rsp-48-2-0206.xml#L191-L208
[2] http://scielohomolog.parati.ag/Artigo/
[3] https://github.com/scieloorg/packtools/blob/master/tests/samples/0034-8910-rsp-48-2-0206.xml#L87-L96

**Comment by leticiaquino** [comment]
haha ok @jfunez , vamos lá:

Antes de tudo, a respeito de idiomas, informo que utilizamos o @xml:lang apenas para traduções, exemplo:
```<trans-title-group xml:lang="">``` (o ```<trans-title>``` não.);
```<trans-abstract xml:lang="">``` ;

Exceção: 
* ```<article>```; 
* ```<sub-article>```; 
* ```<response>```;
* Tabelas e figuras com legendas traduzidas [1].

Isso porque uma vez inserido o @xml:lang em ```<article>```, todo o documento herda o idioma inserido no elemento ```<article>```.

### Abstract e trans-abstract
Considerar apenas os cenários abaixo:

* processando uma tradução, e o a abstract esta em: sub-article[lang]/front-stub/trans-abstract/[lang]
* processando uma tradução, e o a abstract esta em: article[lang]/front/article-meta/trans-abstract/

### Subject

No canto superior direito do layout

### About the authors:

As afiliações aparecem em:

* article/front/article-meta
* article/front/article-meta/contrib-group
* sub-article/front-stub
* sub-article/front-stub/contrib-group

### Financiamento

Na verdade, as informações que constam em ```<funding-group>```, ```<funding-statement>``` são utilizadas para gerar indicadores, então não há a necessidade de apresentar esse dado.

<br/>
<br/>

[1] http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#legenda-traduzida
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#legendas-traduzidas

**Comment by leticiaquino** [comment]
@jfunez 
Obs.: dependendo do documento, os autores e afiliações podem não aparecer em ```<sub-article>```.
Ex.: se o artigo traduzido não apresentar afiliações traduzidas, não duplicamos o dados já marcado em ```<article-meta>```. Identificamos autores e afiliações em ```<sub-article>``` apenas se for apresentado afiliação traduzida. Veja o exemplo abaixo:

**Afiliação no idioma original do artigo:**
PhD, Associate Professor, Escola de Enfermagem, Universidade de São Paulo, São Paulo, SP, Brazil

**Afiliação traduzida:**
PhD, Professor Associado, Escola de Enfermagem, Universidade de São Paulo, São Paulo, SP, Brasil

**Comment by jfunez** [comment]
@leticiaquino segue uma captura de tela do artigo com o código atualizado.
pode ver também nesse link: https://cloud.githubusercontent.com/assets/805749/11100334/c8df91e6-8897-11e5-9763-80e80476b863.png
Se você encontrar algum problema no resultado, pode reportar logo. 
Logo podemos atualizar seu setup para continuar com os tests. 

![screen shot 2015-11-11 at 17 13 01](https://cloud.githubusercontent.com/assets/805749/11100334/c8df91e6-8897-11e5-9763-80e80476b863.png)

**Comment by leticiaquino** [comment]
Hey @jfunez , verifiquei o artigo enviado. Segue abaixo minhas observações:

### Data de publicação
No layout não foi considerado a data de publicação do documento.
Por favor, inserir a informação que consta em: article/front/article-meta/pub-date

### Seção
Há a possibilidade de inserir a seção antes do título?
Verifiquei que aparece no canto superior direito, mas acredito que o ideal seria disponibilizar antes de título.

### Informação de correspondência
Juan, nesse arquivo o label de correspondência é "con1" no xml?
É o valor que consta em "```<xref ref-type="corresp" rid="con1"/>```"?
Caso a correspondência não apresente um ```<label>``` e as tags de ```<xref>``` foram inseridas "fechadas", sugiro não incluir automaticamente um dado.
Entretanto, se essa informação for essencial para o documento, sugiro incluir (para correspondência) um símbolo, exemplo: o asterisco.

### Sugestão para os quadros "About the authors:" e "Authors notes:"
Há a possibilidade de inserir a função de expandir e colapsar? se sim, talvez seja interessante incluir.. o que você acha?


### Palavras-chave
Notei que as palavras-chave não apresentam nenhum separador como "ponto e vírgula", "vírgula" etc.. há apenas espaços entre cada palavra-chave. 
Por gentileza, inserir um separador para esse dado.

### Sumário
O Sumário ao lado acompanha o texto enquanto o usuário percorre o documento?
não consigo saber por aqui :worried:

![sumario](https://cloud.githubusercontent.com/assets/4397365/11118637/70640b12-892a-11e5-983a-76073dbe65eb.jpg)

### Seções no body
Me parece que não há diferença entre tamanho de fonte para seções e subseções..
Veja o caso da seção "Results" que logo abaixo apresenta a subseção "Clinical manifestations of HVOD". não há diferença..
A menos que no documento .xml esse dado não tenha sido identificado corretamente..

### Tabelas
As tabelas desse documento não apresentam label e caption? ou só não está apresentado na página?

### Referências
As referências parecem estar boas, mas.. verificando a ideia de inserir uma bolinha com o número de cada ref, me parece que ficou um pouco estranho..
É realmente necessário apresentar o ponto? 
se sim, há a possibilidade de pelo menos diminuir a bolinha?

outra coisa, pensando na ideia do layout talvez seja interessante não apresentar, assim mantemos um certo 'padrão SciELO'. Além de que o SciELO possui aquela funcionalidade de "Como citar" (How to cite this article) e nesse "como citar" podemos apresentar as refs com o ponto, se existir.

(Quando você me perguntou ontem, eu não estava pensando nesse padrão apresentado.. desculpe)

**Comment by jfunez** [comment]
@leticiaquino meus comentários entre linhas:

#### Data de publicação
> No layout não foi considerado a data de publicação do documento.
> Por favor, inserir a informação que consta em: article/front/article-meta/pub-date

Sim foi considerado, esta bem no final da página, abaixo da seção: ``History:`` em particular aonde diz: ``Publicação digital: 2015``.
 O valor: 2015, é o formado a partir de xml:
```xml
<pub-date pub-type="epub"><year>2015</year></pub-date>
```
A frase:  ``Publicação digital:`` é resultado de que atributo: ``@pub-type='epub'``. 
Caso o atributo seja: ``@pub-type='ppub-epub'`` a frase seria: ``Publicação impressa:``.
E no caso que a tag: **pub-date** tenha os outras tags: ``<day>``, ``<month>``,``<season>`` (além do ``<year>`` claro) também são exibidas como pode ver nas outras linhas do history.
Finalmente, a decissão de colocar esssa informação ali é porque assim aparece no mockup [0] só que nele o título é: *Data de publicação* mas como mistura data de publicação com outras datas, decidimos trocar por *History* e acoplar o <pub-date> com <history> .
Claro que se tiver alguma outra sugestão pode ser analisada.

#### Seção

> Há a possibilidade de inserir a seção antes do título?
> Verifiquei que aparece no canto superior direito, mas acredito que o ideal seria disponibilizar antes de título.

sim, no problem, podemos provar e ver como fica.

#### Informação de correspondência
> Juan, nesse arquivo o label de correspondência é "con1" no xml?

Não, não tem label e nesse caso como alternativa é utilizado o atributo: @id. que no caso seria:
```<corresp id="con1">...```.
> Caso a correspondência não apresente um <label> e as tags de <xref> foram inseridas "fechadas", sugiro não incluir automaticamente um dado.

Casualmente quando estava vendo isso, consultei a Gustavo, e ele sugeriu de consultar a Solange, quem falou que esses dados (tanto a xref do autor, como a informação de corresp) tem que ser exibido sim, mas não temos uma definição de que fazer nestes casos sem label. 
A política por enquanto é: usar o <label> quando estiver presente. se não, usar o @id se não ... 
...
...
(ainda não temos uma definição geral nem caso a caso)
Pode ver por exemplo que nas footnotes, aonde não tem nem label, nem @id, decidimos colocar o simbolo "dagger/obelisk" [1]. Poderia ser asterisco ou qualquer outro.
Não sei se existe algum símbolo "standard" para estas situações, ou se fica ao gosto do freguês.

#### Sugestão para os quadros "About the authors:" e "Authors notes:"

> Há a possibilidade de inserir a função de expandir e colapsar? se sim, talvez seja interessante incluir.. o que você acha?

Sim, concordo, mas nesta fase não estamos incluindo nada de código javascript o que seria necessário para fazer esta funcionalidade. Mas esta nas expectativas futuras.

#### Palavras-chave
ok

#### Sumário

não acompanha, até pq a solução mais fácil era com javascript, mas como comentado anterior não estamos incorporando nenhum código javascript por enquanto. vou tentar fazer sem javascript. se não ficaria para futuros releases.

#### Seções no body

vou revisar.

#### Tabelas

> As tabelas desse documento não apresentam label e caption?

não, não apresentam.
o xml é assim:
```xml
<table-wrap id="t01">
    <graphic mimetype="image" xlink:href="1414-431X-bjmbr-1414-431X20154563-gt001.tif"/>
</table-wrap>
```

#### Referências
> É realmente necessário apresentar o ponto? 

Como é uma questão a ser discutida, até pela equipe de SPS, assim que vocês tiverem uma decisão, pode ser implementada. 
Obs. O ponto bem no dado, (mixed-citation), agora nenhum ponto é inserido no código.

> se sim, há a possibilidade de pelo menos diminuir a bolinha?
> ...outra coisa, pensando na ideia do layout talvez seja interessante não apresentar, ...

A versão atual esta baseada no mockup, então estamos meio amarrados em algumas escolhas, mas podemos testar para comparar.

> Além de que o SciELO possui aquela funcionalidade de "Como citar"

estamos contemplando isso (como aparece no mockup) mas só para quando montar o site, e não nesta parte de previsualização. Mesma coisa para a informação de atlmetrics e métricas de downloads, etc.

Vou ajustar as pendências e voltaremos com mais novidades. Qualquer comentário é bem-vindo como sempre.

[0] http://scielohomolog.parati.ag/Artigo/
[1] https://en.wikipedia.org/wiki/Dagger_%28typography%29

**Comment by leticiaquino** [comment]
@jfunez  abaixo meus comentários:

### Data de publicação
vou verificar melhor essa questão de data de publicação, pois não ficou muito claro para mim.. :sweat_smile:

### Correspondência
esse símbolo "dagger" geralmente é utilizado para identificar informações como "in memoriam", para autores falecidos... talvez não seja uma boa..

Para correspondência há a possibilidade de, nesses casos, incluir aquele símbolo U+2709 (dos Dingbat) que representa um envelope? pode ser que fique mais claro.

**Comment by jfunez** [comment]
> esse símbolo "dagger" geralmente é utilizado para identificar informações como "in memoriam", para autores falecidos... talvez não seja uma boa..

:cold_sweat: LOL

> Para correspondência há a possibilidade de, nesses casos, incluir aquele símbolo U+2709 (dos Dingbat) que representa um envelope? pode ser que fique mais claro.

:+1: ótima ideia, vou trocar por esse envelope então.

**Comment by gustavofonseca** [comment]
Marcado como inválido pois o gerador de HTML foi reimplementado.
