### ISSUE TITLE
<xref> de autor e <label> de afiliações devem estar em <sup>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#65]
Verifiquei que o previewer não apresenta nenhuma formatação para os `<xref>`de autores (ex.: `<xref ref-type="aff" rid="aff1">1</xref>`) e quando há mais que um `<xref>`de autor, o programa mantém os números juntos, dando a impressão de que é um único número em vez de dois. Veja:

![xrefs-previewer](https://cloud.githubusercontent.com/assets/4397365/10524897/5070eb32-7358-11e5-9f43-abb3c0bf7eda.jpg)

Notei também que o programa apresenta como link um elemento "fechado": `<xref ref-type="corresp" rid="con1"/>`. Informo que elementos "fechados" não devem aparecer no previewer.

Obs: `<xref>`do tipo "aff" e "bibr" devem ser apresentadas em **sup**

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#xref

**Comment by jfunez** [comment]
> Verifiquei que o previewer não apresenta nenhuma formatação para os <xref>de autores (ex.: <xref ref-type="aff" rid="aff1">1</xref>) e quando há mais que um <xref>de autor, o programa mantém os números juntos, dando a impressão de que é um único número em vez de dois.

suspeito que na instalação que vc esta usando não esta incluindo o CSS para os ajustes estéticos, que por exemplo separa os número dos links. podemos resolver isso te enviando o CSS necessário e ajustando o comando que você execute. 
adjunto imagen para que você veja como fica com a inclusão do CSS.

>Notei também que o programa apresenta como link um elemento "fechado": ``<xref ref-type="corresp" rid="con1"/>``.
o dado/valor que aparece (con1) é obtido do xml (attributo "@rid") se existir, e caso contrario nomeia os links como aff1, aff2, aff3....affx por exemplo. pode ver mais informação aqui: https://github.com/scieloorg/packtools/blob/html-generator/packtools/catalogs/htmlgenerator/root-html-1.2.xslt#L758
todos os links nesta parte aparecem com o tag ``<sup>`` 
teríamos que estudar estes casos.

grato pelo feedback, aguardo os comentários.
![screen shot 2015-10-15 at 16 36 13](https://cloud.githubusercontent.com/assets/805749/10525997/66e9097a-735e-11e5-9c53-d3c0409092ba.png)

**Comment by gustavofonseca** [comment]
Marcado como inválido pois o gerador de HTML foi reimplementado.
