### ISSUE TITLE
label de nota de rodapé aparece em linha diferente da nota

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#66]
Notei que o label da nota de rodapé aparece acima da nota. Veja:

![notaderodape-previewer](https://cloud.githubusercontent.com/assets/4397365/10525556/c6cef758-735b-11e5-8e98-fdfb29edc60c.jpg)

Verificar a possibilidade de manter o label e a descrição numa mesma linha.

**Comment by jfunez** [comment]
sim, é por causa do CSS, que eu comentei em outro issue.
grato pelo feedback.

**Comment by gustavofonseca** [comment]
Marcado como inválido pois o gerador de HTML foi reimplementado.
