### ISSUE TITLE
Tabelas e figuras são apresentadas abaixo de referências bibliográficas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#67]
Percebi que tabelas e figuras são apresentadas após as referências bibliográficas.

![objetos-aposrefs](https://cloud.githubusercontent.com/assets/4397365/10525691/7f769482-735c-11e5-9201-26758a01183e.jpg)

Verificar a possibilidade de tabelas e figuras serem apresentadas logo abaixo da primeira chamada no corpo do texto.

**Comment by jfunez** [comment]
@leticiaquino nos meus tests aparecem dentro do corpo do texto, e abaixo uma agrupamento das tableas e figuras. o motivo disso é que assim foi definido no mockup do novo site.

**Comment by gustavofonseca** [comment]
Marcado como inválido pois o gerador de HTML foi reimplementado.
