### ISSUE TITLE
instalacao no UBUNTU 14 LTS

### ISSUE THREAD

**Issue by ppKrauss** [scieloorg/packtools#72]
Interessante indicar no README para usuários UBUNTU.

A primeira tentativa de `pip install packtools`  foi interrompida pelo erro "Is libxml2 installed?". Depois de  `sudo apt-get install libxml2-dev libxslt1-dev python-dev` o fui ainda necessário acrescentar o `sudo`. Enfim, sucesso com  `sudo pip install packtools` .

------
NOTAS

Apesar da  *libxml2* estar rodando com outras aplicações (ex. PHP), foi necessário o `apt-get`. Mensagens na primera tentativa:

```
pip install packtools
Requirement already satisfied (use --upgrade to upgrade): packtools in /home/peter/gits/src/packtools
Downloading/unpacking lxml>=3.3.4 (from packtools)
  Downloading lxml-3.5.0.tar.gz (3.8MB): 3.8MB downloaded
  Running setup.py (path:/tmp/pip_build_root/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.5.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
....
*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by gustavofonseca** [comment]
Provavelmente você precisou dos privilégios de superusuário por ter executado o ``pip install packtools`` com o python do sistema (*system python*).

**Comment by gustavofonseca** [comment]
Acrescentei um link para o guia de instalação da lib lxml, e penso que não devo ir além disso.

**Comment by ppKrauss** [comment]
Ok, indicar as dependências já ajuda bastante o navegante desavisado (!). 

-----
Comentários finais:

* o site [lxml.de](http://lxml.de/installation.html)  indica uma linha `apt-get` diferente da que homologuei, por uma sutileza: usei `libxslt1-dev` e ele usa `libxslt-dev`... [Aqui](http://stackoverflow.com/a/18726520)  e [aqui](http://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu#comment25842631_6504860) reforçam que precisava ser com o `1`.

* UBUNTU é bastante popular... Atualmente o v14-LTS é a principal referência para homologações. Em abril teremos o v16-LTS (kernel4), que vai remover o Python 2 (!), assim também será interessante comentar algo sobre "Python 2 vs 3" se houverem restrições a Python3.

* acho que não deixei claro. `sudo pip` não funciona num primeiro momento, qualquer tentativa vai dar erro, mesmo com `sudo`... A demanda por `apt-get` extra (pela lxml) pode não ser óbvia e "dar medo" para quem está testando num server... 

Por conta dessas picuinhas todas, talvez possa valer a pena [abrir aqui a Github-Wiki](https://github.com/scieloorg/packtools/wiki) para relatos de homologações em Ubuntu, Windows, etc. para a comunidade de usuários também poder  se ajudar, sem importunar os desenvolvedores ou poluir o README.

Resultado do `stylechecker --sysinfo` (v0.9.0.dev20160128) no UBUNTU 14 LTS, 

```json
{
  "libxml_compiled_version": "2.9.1", 
  "libxml_version": "2.9.1", 
  "libxslt_compiled_version": "1.1.28", 
  "libxslt_version": "1.1.28", 
  "lxml_version": "3.5.0.0", 
  "packtools_version": "0.9.0", 
  "python_version": "2.7.6", 
  "system_path": [
    "/usr/local/bin", 
    "/usr/local/lib/python2.7/dist-packages/packtools-0.9.0.dev20160128-py2.7.egg", 
    "/usr/local/lib/python2.7/dist-packages/picles.plumber-0.10-py2.7.egg", 
    "/usr/lib/python2.7", 
    "/usr/lib/python2.7/plat-x86_64-linux-gnu", 
    "/usr/lib/python2.7/lib-tk", 
    "/usr/lib/python2.7/lib-old", 
    "/usr/lib/python2.7/lib-dynload", 
    "/usr/local/lib/python2.7/dist-packages", 
    "/usr/lib/python2.7/dist-packages", 
    "/usr/lib/python2.7/dist-packages/PILcompat", 
    "/usr/lib/python2.7/dist-packages/gtk-2.0", 
    "/usr/lib/python2.7/dist-packages/ubuntu-sso-client"
  ], 
  "xml_catalog_files": "/usr/local/lib/python2.7/dist-packages/packtools-0.9.0.dev20160128-py2.7.egg/packtools/catalogs/scielo-publishing-schema.xml"
}
```

Repare que foi tudo orientado a python2, de modo que será diferente (ou dará erro) no 16LTS.

**Comment by gustavofonseca** [comment]
O que você acha de contribuir com uma seção de "troubleshoot" para
usuários de ubuntu? Podemos acrescentar na documentação oficial[1], que
ainda está em fase bastante incipiente.

Sobre a questão Python 2 vs 3, na realidade o packtools é escrita em
Python 3 com compatibilidade para Python 2.7. Atualmente é homologado
para uso com Python 2.7, 3.3 e 3.4 (conforme é possível verificar no
software de CI[2]) 

[1] http://packtools.readthedocs.org 
[2] https://travis-ci.org/scieloorg/packtools 

-- 
-Gustavo

Em Sáb 30 jan. 2016, às 21:13, Peter escreveu:

**Comment by ppKrauss** [comment]
Seção de "troubleshoot" no guia, ótima ideia (!), ok, posso ajudar.
