### ISSUE TITLE
Considerar inserção de campo para "arrastar" arquivos para upload

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/packtools#74]
A opção de "arrastar" arquivos para upload facilita a utilização, uma vez que deve-se carregar os arquivos individualmente para validação.

Exemplo: validador da [JATS4R] (http://jats4r.org/validator/)

`Como ficaria:`

![sem titulo](https://cloud.githubusercontent.com/assets/11942249/12780564/c49368e2-ca55-11e5-808a-d7d9d9748585.png)

**Comment by lpanebr** [comment]
3 vivas para o Renato!

**Comment by renatogaldino** [comment]
:stuck_out_tongue_winking_eye:

**Comment by gustavofonseca** [comment]
Legal. Movi o ticket para o projeto certo.
