### ISSUE TITLE
[packtools] Identificar/diferenciar mensagens de validações externas

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#75]
Conforme ilustrei no comentário do #18 sobre o uso de arquivo schematron externo as mensagens ficam agrupadas juntamente com as validações específicas do SPS em `"sps_errors"`.

Considerando que usuários podem criar regras variadas para validar o conteúdo muito além da SPS pode ser interessante identificar/diferenciar as mensagens geradas dessa forma.

Imagino duas formas:
- um grupo separado: `"external_validation"`, ou
- diferenciar  mensagem: `"external validation": "Element 'publisher-name': Should be 'ABM, ABC, ABPol'."`

**Comment by gustavofonseca** [comment]
E você consegue apontar um caso de uso em que a diferenciação seria
necessária ou desejável?

-- 
-Gustavo

Em Qua 3 fev. 2016, às 10:53, Luciano escreveu:

**Comment by lpanebr** [comment]
Semanticamente as validações externas podem não ter nada a ver com a SPS, o
que justificaria um novo grupo... mas não acho que justifica o esforço
mesmo..

Um caso de uso (meio fraco) seria quando se por exemplo houvesse um
repositório de validações externas poderia ocorrer de prestadores usarem e
reportarem erros em validações externas no grupo scielo..

Eu por exemplo vou usar para fazer as validações "associadas" (acho q foi
esse termo que vc usou) que são aquelas específicas de um journal, como por
exemplo:
 - prefixo ou padrão de formação do DOI
 - validar os dados do arquivo csv Metadados dos periódicos[1]
 - etc...

Mas, diferenciar entre externas e SPS na verdade basta eu mesmo padronzar o
início das minhas mensagens do `<assert>`...

[1]
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/index.html#metadados-dos-periodicos

**Comment by gustavofonseca** [comment]
Entendi. Faz sentido mesmo. =]

-- 
-Gustavo

Em Qua 3 fev. 2016, às 14:45, Luciano escreveu:

**Comment by lpanebr** [comment]
Legal! 

Por hora me resolvi com a mensagem mesmo :-)

![image](https://cloud.githubusercontent.com/assets/129185/12789716/1fbc5c3a-ca86-11e5-8159-b2dead70a0d5.png)

**Comment by gustavofonseca** [comment]
Estou trabalhando em uma prova de conceito dessa funcionalidade que teria a saída no seguinte formato:

```
stylechecker --extrasch tests/samples/sample_schematron.sch --extrasch @scielo-br tests/samples/0034-8910-rsp-48-2-0216.xml
Please wait, this may take a while...
[
 {
   "_xml": "/Users/gustavofonseca/prj/packtools/tests/samples/0034-8910-rsp-48-2-0216.xml",
   "assets": [],
   "dtd_errors": [],
   "is_valid": false,
   "sps_errors": {
     "@scielo-br": [
       {
         "apparent_line": 17,
         "message": "Element 'article-meta': Missing element article-id with pub-id-type=\"doi\"."
       }
     ],
     "built-in": [
       {
         "apparent_line": 5,
         "message": "Element 'journal-meta': Missing element journal-id with journal-id-type=\"publisher-id\"."
       },
       {
         "apparent_line": 107,
         "message": "Element 'abstract': Unexpected attribute xml:lang."
       },
     "tests/samples/sample_schematron.sch": [
       {
         "apparent_line": 6,
         "message": "Element 'journal-id': Invalid NLM title."
       }
     ]
   }
 }
]
```

Note que no exemplo são passados 2 schemas externos: sendo o primeiro um built-in do packtools e o segundo do usuário. 

Sugestões, @lpanebr?

**Comment by lpanebr** [comment]
Legal @gustavofonseca 

 - Acho que usar o path para identificar os esquemas externos é a melhor solução. Dessa forma podemos agrupar os esquemas genéricos e  específicos de journals em diretórios diferentes. :+1: 
 - No caso do esquema built-in é possível indicar qual foi usado? Exemplo: "built-in@sps-1.2", "built-in@sps-1.3" etc

**Comment by gustavofonseca** [comment]
Hm é possível sim indicar qual schema foi carregado automaticamente. É importante o prefixo "built-in"? Pensei em algo como:

```
stylechecker --extrasch tests/samples/sample_schematron.sch --extrasch @scielo-br tests/samples/0034-8910-rsp-48-2-0216.xml
Please wait, this may take a while...
[
  {
    "_xml": "/Users/gustavofonseca/prj/packtools/tests/samples/0034-8910-rsp-48-2-0216.xml",
    "assets": [],
    "dtd_errors": [],
    "is_valid": false,
    "sps_errors": {
      "@scielo-br": [
        {
          "apparent_line": 17,
          "message": "Element 'article-meta': Missing element article-id with pub-id-type=\"doi\"."
        }
      ],
      "@sps-1.5": [
        {
          "apparent_line": 5,
          "message": "Element 'journal-meta': Missing element journal-id with journal-id-type=\"publisher-id\"."
        },
      "tests/samples/sample_schematron.sch": [
        {
          "apparent_line": 6,
          "message": "Element 'journal-id': Invalid NLM title."
        }
      ]
    }
  }
]
```

**Comment by gustavofonseca** [comment]
ps.: o artigo anterior possui ``/article/@specific-use == "sps-1.5"``.

**Comment by lpanebr** [comment]
Acho importante/interessante identificar qual das validações é a carregada a partir do `/article/@specific-use` presente no arquivo. Ainda, se possível, talvez fosse interessante ela ser exibida antes das adicionais não? Talvez manter o built-in...?

**Comment by gustavofonseca** [comment]
O único caso de uso que consigo me imaginar querendo saber exatamente qual schema foi carregado automaticamente é na depuração de um erro ou comportamento inexperado da aplicação. Não consigo imaginar um caso de uso relacionado a produção e validação dos XMLs. Estou perdendo algo? Poderia dar mais detalhes sobre essa opinião com base na tua experiência?

**Comment by lpanebr** [comment]
Nos meses que antecedem a deprecação definitiva de uma SPS ocorre de
exportarmos arquivos usando a nova e a antiga e imaginei que seria útil
para que exporta 20-30 artigo por dia ter essa info ali simplesmente...
 pensei que, no mínimo não iria atrapalhar.. poderia ajudar se o arquivo
est;a na 1.5 e o operado passar um esquema extra @sps-1.5.. ele teria a
chance de perceber que esqueceu de mudar um parâmetro.. num sei.. é mais
intuição acho..

**Comment by gustavofonseca** [comment]
> Nos meses que antecedem a deprecação definitiva de uma SPS ocorre de exportarmos arquivos usando a nova e a antiga e imaginei que seria útil para que exporta 20-30 artigo por dia ter essa info ali simplesmente... pensei que, no mínimo não iria atrapalhar.. 

Se entendi bem serve para referência e quem sabe classificação, certo?. Se sim, e se eu incluir no mesmo nível da chave __xml_, por exemplo a chave _declared_sps_version_ contendo o valor do atributo `article/@specific-use`?

> poderia ajudar se o arquivo est;a na 1.5 e o operado passar um esquema extra @sps-1.5.. ele teria a chance de perceber que esqueceu de mudar um parâmetro.. num sei.. é mais intuição acho..

Hm aqui eu não entendi.

**Comment by lpanebr** [comment]
assistiu Frozen?

let it go, let it go...

**Comment by gustavofonseca** [comment]
Não assisti. Eles produzem XML no filme? 
Ok, vou fechar o ticket como sem resolução.

**Comment by lpanebr** [comment]
desculpe @gustavofonseca 

meu "let it go" era apenas em relação a identificar qual dos schemas foi carregado automaticamente. 

O output abaixo que você propôs [neste comment](https://github.com/scieloorg/packtools/issues/75#issuecomment-289524762) está perfeita e eu acabei me confundindo e fazendo você perder tempo.

```
stylechecker --extrasch tests/samples/sample_schematron.sch --extrasch @scielo-br tests/samples/0034-8910-rsp-48-2-0216.xml
Please wait, this may take a while...
[
  {
    "_xml": "/Users/gustavofonseca/prj/packtools/tests/samples/0034-8910-rsp-48-2-0216.xml",
    "assets": [],
    "dtd_errors": [],
    "is_valid": false,
    "sps_errors": {
      "@scielo-br": [
        {
          "apparent_line": 17,
          "message": "Element 'article-meta': Missing element article-id with pub-id-type=\"doi\"."
        }
      ],
      "@sps-1.5": [
        {
          "apparent_line": 5,
          "message": "Element 'journal-meta': Missing element journal-id with journal-id-type=\"publisher-id\"."
        },
      "tests/samples/sample_schematron.sch": [
        {
          "apparent_line": 6,
          "message": "Element 'journal-id': Invalid NLM title."
        }
      ]
    }
  }
]
```

Lamento mesmo pela brincadeira infeliz. A verdade é que gosto de colaborar e me sinto importante quando sou mencionado por vc aqui nos tickets. Ontem simplesmente foi um dia muito ruim. 
Desculpe.

**Comment by gustavofonseca** [comment]
Tudo bem, @lpanebr. Eu havia entendido que na realidade não fazia diferença, então decidi não fazer nada e deixar como está. Caso eu tenha entendido errado e essa alteração de fato representar uma melhora no uso do utilitário poderemos retomar a discussão em breve.

**Comment by lpanebr** [comment]
OK, @gustavofonseca. Obrigado.

Eu acredito que seja uma melhoria sim. E a forma abaixo, como você propôs, já resolve pois identifica cada um dos schemas carregados.

```
stylechecker --extrasch tests/samples/sample_schematron.sch --extrasch @scielo-br tests/samples/0034-8910-rsp-48-2-0216.xml
Please wait, this may take a while...
[
  {
    "_xml": "/Users/gustavofonseca/prj/packtools/tests/samples/0034-8910-rsp-48-2-0216.xml",
    "assets": [],
    "dtd_errors": [],
    "is_valid": false,
    "sps_errors": {
      "@scielo-br": [
        {
          "apparent_line": 17,
          "message": "Element 'article-meta': Missing element article-id with pub-id-type=\"doi\"."
        }
      ],
      "@sps-1.5": [
        {
          "apparent_line": 5,
          "message": "Element 'journal-meta': Missing element journal-id with journal-id-type=\"publisher-id\"."
        },
      "tests/samples/sample_schematron.sch": [
        {
          "apparent_line": 6,
          "message": "Element 'journal-id': Invalid NLM title."
        }
      ]
    }
  }
]
```

Qualquer dúvida só dizer.

**Comment by gustavofonseca** [comment]
Após a [modificação](https://github.com/gustavofonseca/packtools/commit/0ae78ab76d4f4e019312c42530a83bd23abf777e), a estrutura de dados ficou assim: 

```
stylechecker --extrasch tests/samples/sample_schematron.sch tests/samples/0034-8910-rsp-48-2-0216.xml
Please wait, this may take a while...
[
  {
    "_xml": "/Users/gustavofonseca/prj/packtools/tests/samples/0034-8910-rsp-48-2-0216.xml",
    "assets": [],
    "dtd_errors": [],
    "is_valid": false,
    "style_errors": {
      "@sps-1.5": [
        {
          "apparent_line": 5,
          "message": "Element 'journal-meta': Missing element journal-id with journal-id-type=\"publisher-id\"."
        },
        {
          "apparent_line": 108,
          "message": "Element 'abstract': Unexpected attribute xml:lang."
        }
      ],
      "tests/samples/sample_schematron.sch": [
        {
          "apparent_line": 6,
          "message": "Element 'journal-id': Invalid NLM title."
        }
      ]
    }
  }
]
```

Note também que a chave ``sps_errors`` foi alterada para ``style_errors``.
