### ISSUE TITLE
Delegar a renderização de fórmulas e equações para o cliente.

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#78]
Se deixar em MathML e usar o [MathJax](https://www.mathjax.org/) ficaria lindo!

No XML:

``` xml
100% crystalline PHBV, which was taken as 109 J g<sup>-1</sup> <xref ref-type="bibr" rid="B021"><sup>21</sup></xref>.</p>
<disp-formula id="e01"><mml:math id="m1">
 <mml:mrow>
  <mml:msub>
   <mml:mi>X</mml:mi>
   <mml:mi>c</mml:mi>
  </mml:msub>
  <mml:mrow><mml:mo>(</mml:mo>
   <mml:mtext>%</mml:mtext>
  <mml:mo>)</mml:mo></mml:mrow><mml:mo>=</mml:mo><mml:mtext> </mml:mtext><mml:mfrac>
   <mml:mrow>
    <mml:mi>Δ</mml:mi><mml:msub>
     <mml:mi>H</mml:mi>
     <mml:mrow>
      <mml:mi>m</mml:mi><mml:mn>1</mml:mn></mml:mrow>
    </mml:msub>
    </mml:mrow>
   <mml:mrow>
    <mml:msub>
     <mml:mi>W</mml:mi>
     <mml:mrow>
      <mml:mi>P</mml:mi><mml:mi>H</mml:mi><mml:mi>B</mml:mi><mml:mi>V</mml:mi></mml:mrow>
    </mml:msub>
    <mml:mo>.</mml:mo><mml:mi>Δ</mml:mi><mml:msubsup>
     <mml:mi>H</mml:mi>
     <mml:mi>m</mml:mi>
     <mml:mn>0</mml:mn>
    </mml:msubsup>
    </mml:mrow>
  </mml:mfrac>
  <mml:mtext>*</mml:mtext><mml:mn>100</mml:mn><mml:mtext> </mml:mtext></mml:mrow>
</mml:math> <label>(1)</label></disp-formula>
</sec>
<sec id="sec234">
<title>2.3.4 Gel Permeation Chromatography (GPC)</title>
```

No browser:
![image](https://cloud.githubusercontent.com/assets/129185/12826444/2c32800c-cb62-11e5-9ea2-d9c900274e35.png)

No HTML:

``` html
[...]
100% crystalline PHBV, which was taken as 109 J g<sup>-1</sup> <a href="#B021" class="xref_href"><sup>21</sup></a>.</p>

Xc(%)= ΔHm1WPHBV.ΔHm0*100     <label for="e01">(1)</label>

</section>
<a id=""></a><section class="">
<header>
<h2>2.3.4 Gel Permeation Chromatography (GPC)</h2></header>
[...]
```

**Comment by gustavofonseca** [comment]
Esse ticket está parecendo mais um desabafo do que uma solicitação de mudança ou informe de erro. A idéia é que o fragmento da equação/fórmula, MathML ou LaTeX, seja injetado no HTML gerado ao invés dos seus valores sem marcação?

**Comment by lpanebr** [comment]
desculpe @gustavofonseca 

Não foi desabafo não rs.. foi falta de habilidade ao reportar.. 

Sim, pelo que entendo o ideal seria isso que você sugere. Injetar o código sem transforma-lo e delegar a renderização para a biblioteca client-side.

Eu sei que Elsevier, Springer e a página beta (fundo amarelo) do scielo usam essa biblioteca. 

![image](https://cloud.githubusercontent.com/assets/129185/12983936/b70d6ece-d0d2-11e5-816c-29f4f83ee474.png)
fonte: http://www.scielo.br/article_plus.php?pid=S1516-14392016005001102&tlng=en&lng=en

**Comment by gustavofonseca** [comment]
@lpanebr, troquei o título do ticket para algo mais alinhado a tarefa. :+1:

**Comment by gustavofonseca** [comment]
Implementado na versão 2.2.
