### ISSUE TITLE
[stylechecker] BUG `--extrasch` não executa patterns criados em `<include>`

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/packtools#79]
Para facilitar estou criando um arquivo common.sch com regras (patterns) gerais e tentando usar `<include href="common.sch"/>` no arquivo principal `acronimo.sch`

Mas parece que o uso da opção `--extrasch` não executa patterns criados em `<include>`...

**Será bug ou ignorância da minha parte?**

A seguir o output pertinente para o comando: 

`stylechecker --extrasch /extra-validations/acronimo.sch artigo.xml`

**Quando pattern está via `<include href="common.sch"/>` no arquivo `common.sch`:**
```json
    "sps_errors": [
      {
        "apparent_line": 12, 
        "message": "EC-CHECK: O 'publisher-name' deve ser 'ABM, ABC, ABPol'."
      }
    ]
```

**Quando pattern está dentro no arquivo `acronimo.sch`:**
```json
    "sps_errors": [
      {
        "apparent_line": 12, 
        "message": "EC-CHECK: O 'publisher-name' deve ser 'ABM, ABC, ABPol'."
      }, 
      {
        "apparent_line": 217, 
        "message": "EC-CHECK COMMON: Nao deve haver 'funding-source' nem 'award-id' dentro de '/article/back/ack/p'"
      }, 
      {
        "apparent_line": 217, 
        "message": "EC-CHECK COMMON: Nao deve haver 'funding-source' nem 'award-id' dentro de '/article/back/ack/p'"
      }, 
      {
        "apparent_line": 217, 
        "message": "EC-CHECK COMMON: Nao deve haver 'funding-source' nem 'award-id' dentro de '/article/back/ack/p'"
      }
    ]
```

**Comment by gustavofonseca** [comment]
Pode anexar o schema aqui para eu testar?

**Comment by lpanebr** [comment]
Oi @gustavofonseca segue arquivo [extra-validations.zip](https://github.com/scieloorg/packtools/files/126750/extra-validations.zip) com arquivos:
 - common.sch
 - mr.sch
 - mr-2015-0496.xml

Obrigado!

**Comment by gustavofonseca** [comment]
Hm, na realidade não trata-se de um bug, mas sim de problemas estruturais no schema _common.sch_.
Experimente trocar seu conteúdo para o seguinte:

`<?xml version="1.0" encoding="utf-8"?>
<pattern id="sempre-erro" xmlns="http://purl.oclc.org/dsdl/schematron">
  <rule context="/article">
    <assert test="false">
        A diretiva *include* está funcionando!
    </assert>
  </rule>
</pattern>`

**Comment by gustavofonseca** [comment]
Pelo que pude perceber analisando o arquivo _common.sch_, vc tinha a intenção de agrupar uma série de _patterns_, certo? O ISO-Schematron não permite isso. A diretiva _include_ literalmente inclui o XML referenciado no ponto onde está a diretiva, com a restrição de que se trate de um XML válido e bem formado.. logo vc só pode incluir _pattern_ e não _schema_.

> “A Schematron include is less flexible than external entities, which support multirooted documents. This gives you the ability to group several patterns or rules in a single document, which a Schematron include doesn't support. ”

Excerpt From: Eric van der Vlist. “Schematron.” iBooks.

**Comment by lpanebr** [comment]
Sim, no common.sch terei validações genéricas que valem para todas as
revistas, e no acronimo.sch as validações associadas à cada revista.

AGora funcionou. Obrigado!
