### ISSUE TITLE
Elemento *aff/country* deve ser obrigatório

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/packtools#83]
Apresentar erro quando não tiver o elemento ```<country```

**Comment by gustavofonseca** [comment]
Segundo a documentação da JATS[1], o elemento **country** pode estar contido nos elementos ``<address>``, ``<addr-line>``, ``<aff>``, ``<collab>`` e ``<corresp>``.  A restrição mencionada por você deve ser aplicada em quais casos? Pode apontar o local na especificação que apoia a tua solicitação?

[1] http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-8m80.html

**Comment by luanaaraujo** [comment]
@gustavofonseca Me refiro  em ```<aff>```.
Segundo o SciELO PS [country](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#country) só aparece em ```<aff>```, e segundo o mesmo ele é obrigatório.

**Comment by gustavofonseca** [comment]
Entendi. Vou marcar esse ticket como um bug.

Só para esclarecer outra coisa, essa frase não está correta:

> Segundo o SciELO PS country só aparece em <aff>

O item **Aparece em** significa[1]: 

> Aparece em: Apresenta o contexto (elemento-pai) onde o elemento em foco é comumente identificado. O fato de um determinado contexto não constar nesta lista não o exclui automaticamente, e a especificação JATS Publishing deve ser consultada.

[1] http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/index.html#convencoes-utilizadas-neste-guia

**Comment by luanaaraujo** [comment]
rss ok @gustavofonseca entendi, na próxima tiro o "só" =P

**Comment by gustavofonseca** [comment]
;)

-Gustavo

Em Qui 3 mar. 2016, às 12:06, luanaaraujo escreveu:
