### ISSUE TITLE
Não indica erro para autor não marcado nas referências

### ISSUE THREAD

**Issue by suelylc** [scieloorg/packtools#85]
Não está indicando erro para ocorrência de autor não marcado em  ref-list/ref/element-citation/person-group
![bug_autor](https://cloud.githubusercontent.com/assets/6921625/13493657/1528705c-e11e-11e5-8800-9ec6acdcd27d.png)

**Comment by gustavofonseca** [comment]
Pode me indicar o ponto na especificação, incluindo sua versão, onde
consta essa regra?

-Gustavo

Em Qui 3 mar. 2016, às 08:59, suelylc escreveu:

**Comment by suelylc** [comment]
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.3-branch/tagset.html#element-citation

Nota:
"Todas as informações de uma referência devem ser marcadas"

Neste caso, o nome de um dos autores que compõe a referência está solto dentro de ```<element-citation>```

**Comment by gustavofonseca** [comment]
Entendi. E no cenário onde o elemento **<person-group>** aparece em **<front>**?

**Comment by gustavofonseca** [comment]
@suelylc alô alô?

**Comment by suelylc** [comment]
Esse problema está ocorrendo em "ref-list/ref/element-citation/person-group"

**Comment by gustavofonseca** [comment]
Sim. Mas **person-group** também pode ocorrer em ``//article-meta//product/person-group``, a regra também se aplica nesse caso?

**Comment by suelylc** [comment]
Sim, em ambos os contextos todos os autores presentes em person-group devem estar marcados

**Comment by gustavofonseca** [comment]
Ok. Por hora só posso implementar a regra para o caso de uso de ``ref/element-citation/person-group``. Vou abrir um ticket no na especificação SciELO PS para que seja explícita a proibição de textos soltos no elemento ``//article-meta//product/person-group``.
