### ISSUE TITLE
[HTMLPreviewer] Programa suprime partes do documento .xml no HTML Previewer

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/packtools#87]
Verificamos que o HTML previewer suprime toda a seção "3. Results And Discussion". Veja a imagem abaixo:

![results-discussions](https://cloud.githubusercontent.com/assets/4397365/14462973/b02d3eca-009f-11e6-9201-2d5fba9b4ef2.jpg)

Envio anexo o arquivo .pdf do documento e por e-mail, o arquivo .xml
[1516-1439-mr-1980-5373-MR-2016-0019.pdf](https://github.com/scieloorg/packtools/files/215177/1516-1439-mr-1980-5373-MR-2016-0019.pdf)

**Comment by gustavofonseca** [comment]
Corrigido.
