### ISSUE TITLE
[HTML Previewer] Não apresenta tabelas codificadas corretamente

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/packtools#89]
Ao passar o arquivo no XPM a tabela se apresenta de forma correta

![image](https://cloud.githubusercontent.com/assets/15328777/16583206/60bca632-428a-11e6-8d13-bc544e87e278.png)

Assim como em homolog.xml

![bug_previewer](https://cloud.githubusercontent.com/assets/15328777/16583259/c5c15c8a-428a-11e6-87f7-0082f115faae.png)

Mas os passar no HTML Previewer ela aparece desconfigurada.

![image](https://cloud.githubusercontent.com/assets/15328777/16583287/fb9fe222-428a-11e6-8772-d22a314946bd.png)

**Comment by gustavofonseca** [comment]
O pré-visualizador foi reimplementado. O erro não é mais reproduzido.
